### ISSUE TITLE
Sporadic errors in importDocument

### ISSUE THREAD

**Issue by aznwarmonkey** [arangodb/arangodb-java-driver#100]
Sporadically I get errors using the importDocument API.  Below is the stacktrace I get

`com.arangodb.ArangoDBException: Response: 400, Error: 400 - expecting a JSON array in the request
	at com.arangodb.internal.velocystream.Communication.checkError(Communication.java:105)
	at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:120)
	at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:40)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:58)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:47)
	at com.arangodb.ArangoCollection.importDocuments(ArangoCollection.java:164)
	at com.arangodb.ArangoCollection.importDocuments(ArangoCollection.java:149)
	at edu.mit.ll.osdi.function.GraphIndexerFunction$1.call(GraphIndexerFunction.java:192)
	at edu.mit.ll.osdi.function.GraphIndexerFunction$1.call(GraphIndexerFunction.java:101)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartition$1.apply(JavaRDDLike.scala:225)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartition$1.apply(JavaRDDLike.scala:225)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$33.apply(RDD.scala:920)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$33.apply(RDD.scala:920)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Do you have any ideas as to why I am having this issue?  The data I am inserting is of type BaseDocument or BaseEdgeDocument

**Comment by mpv1989** [comment]
Which version of ArangoDB and the Java driver do you use and can you please post be sample data of your documents?

**Comment by aznwarmonkey** [comment]
I am using ArangoDB v 3.1.8 in Cluster mode and the latest Java driver version 4.1.8

Here's is an example of my documents.  Please let me know if you need more.  

<img width="763" alt="screen shot 2017-02-05 at 1 13 53 pm" src="https://cloud.githubusercontent.com/assets/4139275/22628644/914d2b68-eba5-11e6-93b4-bcb98ce2f3ef.png">

**Comment by mpv1989** [comment]
Ok. I think I need more to figure out what happen.
Can you post your java code and maybe log-output (log level debug required) when the error occurs?

Thanks
Mark

**Comment by aznwarmonkey** [comment]
Below is the Java code that I am using to insert the doucment.  I will not that this runs in a distributed Spark environment.   I will try to reproduce the issue and get the proper logs.  It sometimes takes 30 mins or longer .  

```java
			public void call(final Iterator<String> iter) throws Exception {

				final ArangoDB.Builder builder = new ArangoDB.Builder();
				builder.host(fArangoDBServers);
				builder.port(fArangoDBPort);

				final ArangoDB arangoDB = builder.build();

				final ArangoDatabase database = arangoDB.db(fArangoDBDatabaseName);

				try {
					final Map<String, List<BaseDocument>> nodeDocumentMapping = new HashMap<String, List<BaseDocument>>();
					final Map<String, List<BaseDocument>> edgeDocumentMapping = new HashMap<String, List<BaseDocument>>();

					while (iter.hasNext()) {
						final JSONObject graphlet = (JSONObject) ((JSONObject) ((JSONObject) new JSONParser()
								.parse(iter.next())).get("message")).get("graph");

						// get the nodes
						final JSONArray nodes = (JSONArray) graphlet.get("nodes");
						LOGGER.info("Number of Nodes:\t" + nodes.size());

						for (int i = 0; i < nodes.size(); i++) {
							final JSONObject node = (JSONObject) nodes.get(i);
							// get the node type
							final String nodeType = ((String) node.get("type")).replaceAll(":", "_");

							// get the node ID
							final String nodeID = (String) node.get("id");

							List<BaseDocument> baseDocuments = nodeDocumentMapping.get(nodeType);
							if (baseDocuments == null) {
								baseDocuments = new ArrayList<BaseDocument>();
								nodeDocumentMapping.put(nodeType, baseDocuments);
							}

							final Map<String, Object> properties = node;

							final BaseDocument document = new BaseDocument(nodeID);
							document.setProperties(properties);

							baseDocuments.add(document);
						}

						// get the edges
						final JSONArray edges = (JSONArray) graphlet.get("edges");

						LOGGER.info("Number of Edges:\t" + edges.size());

						// process edge
						for (int i = 0; i < edges.size(); i++) {
							final JSONObject edge = (JSONObject) edges.get(i);

							// get the node type
							final String edgeType = ((String) edge.get("relation")).replaceAll(":", "_");

							// get the node ID
							final String edgeID = ((String) edge.get("id")).replace(":", "_").replace("|", "_");

							// get the source node
							final JSONObject source = (JSONObject) edge.get("source");
							final String sourceID = ((String) source.get("type")).replaceAll(":", "_") + "/"
									+ (String) source.get("id");

							// get the target node
							final JSONObject target = (JSONObject) edge.get("target");
							final String targetID = ((String) target.get("type")).replaceAll(":", "_") + "/"
									+ (String) target.get("id");

							List<BaseDocument> baseDocuments = edgeDocumentMapping.get(edgeType);
							if (baseDocuments == null) {
								baseDocuments = new ArrayList<BaseDocument>();
								edgeDocumentMapping.put(edgeType, baseDocuments);
							}

							final BaseEdgeDocument document = new BaseEdgeDocument(edgeID, sourceID, targetID);
							document.setProperties(edge);
							baseDocuments.add(document);
						}
					}

					final long t1 = System.currentTimeMillis();
					int countNodes = 0;
					for (final String nodeType : nodeDocumentMapping.keySet()) {
						final ArangoCollection collection = getOrCreateCollection(nodeType, CollectionType.DOCUMENT,
								database);
						final List<BaseDocument> documents = nodeDocumentMapping.get(nodeType);
						countNodes += documents.size();
						collection.importDocuments(documents);
					}
					final long t2 = System.currentTimeMillis();
					LOGGER.info("Node Ingestion time:\t" + (t2 - t1) + " SIZE:\t" + countNodes);

					int countEdges = 0;
					for (final String edgeType : edgeDocumentMapping.keySet()) {
						final ArangoCollection collection = getOrCreateCollection(edgeType, CollectionType.EDGES,
								database);
						final List<BaseDocument> documents = edgeDocumentMapping.get(edgeType);
						collection.importDocuments(documents);
						countEdges += documents.size();
					}
					long t3 = System.currentTimeMillis();
					LOGGER.info("Edge Ingestion time:\t" + (t3 - t2) + " SIZE:\t" + countEdges);

				} finally {
					arangoDB.shutdown();
				}
			}

	/**
	 * @param pCollectionName The collection name to get or create
	 * @param pCollectionType the collection type
	 * @param pArangoDatabase the arango database
	 * @return Returns the {@link ArangoCollection}
	 */
	private ArangoCollection getOrCreateCollection(final String pCollectionName, final CollectionType pCollectionType,
			final ArangoDatabase pArangoDatabase) {
		ArangoCollection collection = pArangoDatabase.collection(pCollectionName);
		try {
			collection.load();
		} catch (ArangoDBException exception) {
			collection = createCollection(pCollectionName, pCollectionType, pArangoDatabase);
		}

		// return the collection
		return collection;
	}

	/**
	 * @param pCollectionName The collection name to create
	 * @param pCollectionType the collection type
	 * @param pArangoDatabase the arango database
	 * @return Returns the {@link ArangoCollection}
	 */
	private ArangoCollection createCollection(final String pCollectionName, final CollectionType pCollectionType,
			final ArangoDatabase pArangoDatabase) {

		// set the collection creation option
		final CollectionCreateOptions collectionCreateOptions = new CollectionCreateOptions()
				.keyOptions(true, KeyType.traditional, 1, 1).type(pCollectionType).replicationFactor(fNumReplication)
				.numberOfShards(fNumShards).indexBuckets(64).waitForSync(true);

		// create collection
		pArangoDatabase.createCollection(pCollectionName, collectionCreateOptions);

		// return the collection name
		return pArangoDatabase.collection(pCollectionName);
	}
```

**Comment by mpv1989** [comment]
Does the error still occur with a newer arangodb version?
