### ISSUE TITLE
ArangoDB Cluster locking issues

### ISSUE THREAD

**Issue by aznwarmonkey** [arangodb/arangodb-java-driver#108]
I am currently doing heavy imports into arango db cluster 3.1.12 (3 coordinators, 3 db server, and 3 agencies) and getting lots of locking errors.  

Is this expected?  If so, what is causing this and is there a good way to handle the errors?  
If not, how do i prevent this from happening?

The collection configured as such

-  replication fator = 2
-  number of shads = 5
-  index buckets = 64

Here's the stacktrace from the java errors 
```java
com.arangodb.ArangoDBException: Response: 500, Error: 18 - lock timeout
	at com.arangodb.internal.velocystream.Communication.checkError(Communication.java:105)
	at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:111)
	at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:40)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:58)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:47)
	at com.arangodb.ArangoCollection.importDocuments(ArangoCollection.java:164)
	at main.StressTest.importTest(StressTest.java:80)
	at main.StressTest.importTest(StressTest.java:86)
	at main.StressTest.importTest(StressTest.java:86)
	at main.StressTest.bulk(StressTest.java:66)
	at main.StressTest.main(StressTest.java:47)
```

Errors from arangodb logs 
```bash
2017-03-03T14:12:30Z [27213] ERROR {cluster} ClusterComm::performRequests: got no answer from server:PRMR-fbc247e9-512d-4812-b12e-a05b0cee2a12:/_db/_system/_api/document/s3100018?isRestore=true with error 4
2017-03-03T14:12:30Z [27213] ERROR {cluster} ClusterComm::performRequests: got no answer from server:PRMR-fbc247e9-512d-4812-b12e-a05b0cee2a12:/_db/_system/_api/document/s3100018?isRestore=true with error 4
2017-03-03T14:12:30Z [27213] ERROR {replication} insertLocal: dropping follower PRMR-fbc247e9-512d-4812-b12e-a05b0cee2a12 for shard s3100018
2017-03-03T14:12:30Z [27213] ERROR {replication} insertLocal: dropping follower PRMR-fbc247e9-512d-4812-b12e-a05b0cee2a12 for shard s3100018
2017-03-03T14:13:27Z [27213] ERROR {cluster} ClusterComm::performRequests: got no answer from server:PRMR-fbc247e9-512d-4812-b12e-a05b0cee2a12:/_db/_system/_api/document/s3100018?isRestore=true with error 4
2017-03-03T14:13:27Z [27213] ERROR {replication} insertLocal: dropping follower PRMR-fbc247e9-512d-4812-b12e-a05b0cee2a12 for shard s3100018
2017-03-03T14:13:31Z [27213] ERROR {cluster} ClusterComm::performRequests: got no answer from server:PRMR-fbc247e9-512d-4812-b12e-a05b0cee2a12:/_db/_system/_api/document/s3100021?isRestore=true with error 4
2017-03-03T14:13:31Z [27213] ERROR {replication} insertLocal: dropping follower PRMR-fbc247e9-512d-4812-b12e-a05b0cee2a12 for shard s3100021
2017-03-03T14:13:31Z [27213] ERROR {cluster} ClusterComm::performRequests: got no answer from server:PRMR-fbc247e9-512d-4812-b12e-a05b0cee2a12:/_db/_system/_api/document/s3100021?isRestore=true with error 4
2017-03-03T14:13:31Z [27213] ERROR {replication} insertLocal: dropping follower PRMR-fbc247e9-512d-4812-b12e-a05b0cee2a12 for shard s3100021
2017-03-03T14:13:31Z [27213] ERROR {cluster} ClusterComm::performRequests: got no answer from server:PRMR-fbc247e9-512d-4812-b12e-a05b0cee2a12:/_db/_system/_api/document/s3100021?isRestore=true with error 4
2017-03-03T14:13:31Z [27213] ERROR {replication} removeLocal: dropping follower PRMR-fbc247e9-512d-4812-b12e-a05b0cee2a12 for shard s3100021
2017-03-03T14:14:44Z [27213] ERROR synchronizeOneShard: long call to syncCollection for shard s3115590 {"barrierId":"12407120","lastLogTick":"12382224","collections":[{"id":"1100145","name":"s3115590"}]} start time:  Fri Mar 03 2017 09:12:20 GMT-0500 (EST) end time:  Fri Mar 03 2017 09:14:44 GMT-0500 (EST)
2017-03-03T14:14:47Z [27213] ERROR {cluster} ClusterComm::performRequests: got no answer from server:PRMR-fbc247e9-512d-4812-b12e-a05b0cee2a12:/_db/STRESS/_api/document/s3115591?isRestore=true with error 4
2017-03-03T14:14:47Z [27213] ERROR {replication} insertLocal: dropping follower PRMR-fbc247e9-512d-4812-b12e-a05b0cee2a12 for shard s3115591
2017-03-03T14:15:52Z [27213] INFO {replication} connected to master at tcp://osdi-01:8529, id 123281029975215, version 3.1, last log tick 14051440
2017-03-03T14:16:03Z [27213] ERROR synchronizeOneShard: long call to syncCollection for shard s3115590 {"barrierId":"14069453","lastLogTick":"14051440","collections":[{"id":"1100145","name":"s3115590"}]} start time:  Fri Mar 03 2017 09:15:52 GMT-0500 (EST) end time:  Fri Mar 03 2017 09:16:03 GMT-0500 (EST)
```

**Comment by neunhoef** [comment]
What seems to be happening here is that the cluster cannot handle the pressure from the import. I have just tried a similar import using the `arangoimp` tool and it worked fine, however, I was using a version in which a known bug of 3.1.12 was fixed. 

Here are some questions to narrow down the problem: 

Are you using a single thread and thus a single connection in your Java client or are you calling importDocuments concurrently over multiple connections? 

How large are the chunks and documents you import? (Ballpark figures are enough) 

Do your DBServers have enough RAM to take the data? Is any server crashing or does the system begin to swap?

How large are your machines (how much memory, disk and how many cores)?

Are you using SSDs or spinning disks?

Would it be possible for us to get the data and programs to do the import?

**Comment by aznwarmonkey** [comment]
Below is my sample application.  It is running in a single thread in a tight loop ingesting 10k documents at a time.  I was having major issues of my arangodb cluster crashing in an Apache Spark environment.  So I created standalone java application to try and reproduce it

For the cluster itself, is there a way i can figure how much RAM to give it?

The machines (3x) specs are:
- 256GB RAM
- SATA HD ( ~50GB available)
- 32 cores

```java
	private static ArangoDB getArangoDB() {

		ArangoDB.Builder builder = new ArangoDB.Builder();
		builder.host("osdi-m", 8530);
		builder.host("osdi-01", 8530);
		builder.host("osdi-02", 8530);
		builder.timeout(Integer.MAX_VALUE);

		return builder.build();
	}

	private static void bulk() {
		final ArangoDB arangoDB = getArangoDB();
		try {
			while (true) {
				importTest(arangoDB);
			}
		} finally {
			arangoDB.shutdown();
		}
	}

	private static void importTest(final ArangoDB pArangoDB) {
		try {
			final ArangoDatabase arangoDatabase = pArangoDB.db(dbName);
			final ArangoCollection collection = getOrCreateCollection(collectionName, CollectionType.DOCUMENT,
					arangoDatabase);
			final long t1 = System.currentTimeMillis();
			DocumentImportOptions documentImportOptions = new DocumentImportOptions().waitForSync(true);
			collection.importDocuments(createBaseDocument(10000), documentImportOptions);
			final long t2 = System.currentTimeMillis();
			System.out.println("Time:\t" + (t2 - t1));
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private static List<BaseDocument> createBaseDocument(int pSize) {
		final List<BaseDocument> documents = new ArrayList<BaseDocument>();

		for (int i = 0; i < pSize; i++) {

			final BaseDocument baseDocument = new BaseDocument(UUID.randomUUID().toString());
			baseDocument.addAttribute("attribute", UUID.randomUUID().toString());
			documents.add(baseDocument);
		}
		return documents;
	}
```

**Comment by mpv1989** [comment]
Since this issue is very old I will close it, feel free to open it again if this is still a problem to be solved
