### ISSUE TITLE
Unpredictable query failure with IOException or CancellationException

### ISSUE THREAD

**Issue by choesang** [arangodb/arangodb-java-driver#117]
We are using arangoDB (3.1.17) and arangodb-java-driver version(4.1.11)

We were previously using arangodb-java-driver (3.1.X) and had no problem at all but since moving over to 4.1.x it started to behave very unpredictably. I even had to implement my own serializer/deserializer for java util Date because the driver could not deserialize it back. 
I say unpredictable because it fails sometimes and other times works just fine. I am referring to the following 2 queries: a velocypack and AQL 

`arangoDB.collection(collectionName).documentExists(id);`

`String countQuery = "RETURN COUNT(FOR v IN " + collectionName + " FILTER v." + name + " == @" + name + " && IS_NULL(v.deleted) RETURN v)";`

```
10:01:02,449 ERROR [com.arangodb.internal.velocystream.MessageStore] (pool-231-thread-1) The socket is closed.: java.io.IOException: The socket is closed.
        at com.arangodb.internal.velocystream.Connection$1.call(Connection.java:140)
        at com.arangodb.internal.velocystream.Connection$1.call(Connection.java:134)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

```
10:21:43,767 ERROR [stderr] (Thread-48) Exception in thread "Thread-48" java.util.concurrent.CancellationException
10:21:43,767 ERROR [stderr] (Thread-48)         at java.util.concurrent.FutureTask.report(FutureTask.java:121)
10:21:43,767 ERROR [stderr] (Thread-48)         at java.util.concurrent.FutureTask.get(FutureTask.java:192)
10:21:43,767 ERROR [stderr] (Thread-48)         at com.arangodb.internal.velocystream.ConnectionSync.write(ConnectionSync.java:87)
10:21:43,767 ERROR [stderr] (Thread-48)         at com.arangodb.internal.velocystream.CommunicationSync.send(CommunicationSync.java:139)
10:21:43,767 ERROR [stderr] (Thread-48)         at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:123)
10:21:43,767 ERROR [stderr] (Thread-48)         at com.arangodb.internal.velocystream.CommunicationSync.authenticate(CommunicationSync.java:144)
10:21:43,767 ERROR [stderr] (Thread-48)         at com.arangodb.internal.velocystream.CommunicationSync.authenticate(CommunicationSync.java:40)
10:21:43,767 ERROR [stderr] (Thread-48)         at com.arangodb.internal.velocystream.Communication.connect(Communication.java:79)
10:21:43,767 ERROR [stderr] (Thread-48)         at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:120)
10:21:43,767 ERROR [stderr] (Thread-48)         at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:40)
10:21:43,767 ERROR [stderr] (Thread-48)         at com.arangodb.internal.velocystream.Communication.execute(Communication.java:95)
10:21:43,767 ERROR [stderr] (Thread-48)         at com.arangodb.ArangoCollection.documentExists(ArangoCollection.java:525)
10:21:43,767 ERROR [stderr] (Thread-48)         at com.arangodb.ArangoCollection.documentExists(ArangoCollection.java:508)
```

I have the feeling that it might have to do with how connections are managed by arango driver. Any ideas what is going wrong?

**Comment by mpv1989** [comment]
Can you provide some more information of your setup (singleserver/cluster, client single/multi threaded)?
It would also be helpful if you can share a bit source code from your usage of the driver api.

If you can also give me example code of your java.util.Date serialization problem. The driver supports java.util.Date and this is the first time I hear someone has problems with that.

**Comment by choesang** [comment]
The behaviuor i m

**Comment by choesang** [comment]
The behavior i mentioned is very similar to `https://github.com/arangodb/arangodb/issues/2305` The documentExists feature behaves sporadically. We were also using previously the 3.1.x and moving to 4.1.x caused all the problem. We are working in a javaEE environment and were creating the arangoDB connection builder in a CDI bean and injecting it into all the DAO objects. It worked fine before but with the new driver, realized that this configuration caused problem. The arangoDB connection is instantiated every time. It currently fixed the problem by making the ArangoDB connection builder as a singleton.

**Comment by mpv1989** [comment]
@choesang are you injecting an instance of `ArangoDB` or `ArangoDB.Builder` to your DAO objects? I try to reproduce your issue.

I already optimized some code in the driver for multi thread use, you can already test it with the current snapshot `4.1.12-SNAPSHOT`. It were just small things, I don't think it will fix your problem, but you never know.

**Comment by choesang** [comment]
@mpv1989 The arango connection is issue is solved at the moment.

> If you can also give me example code of your java.util.Date serialization problem. The driver supports java.util.Date and this is the first time I hear someone has problems with that.

I get once a while NumberFormatException when deserializing Date.

```
{
  "created": "2017-04-07T13:49:58.450Z",
  "enabled": true,
  "encryptedPassword": "dAYPmJa8b9UWZkUC4iwlzKFHeYBvmfB7RtDh+hmRxJ8=",
  "salt": "NU1KDguxwO5gV8FMwoqMug==",
  "updated": "2017-04-07T13:49:58.450Z"
}
```

```
public class User {
Date created;
Date updated;
}
```

```
protected T getUniqueResult(Iterator<T> cursor) throws ArangoDaoException, NoResultException, NonUniqueResultException {
        final T result = cursor.hasNext() ? cursor.next() : null;
        if (result == null) {
            throw new NoResultException("No result found");
        }
        if (cursor.hasNext()) {
            final String message = "Non-unique document in " + collectionName;
            throw new NonUniqueResultException(message);
        }
        return result;
    }
```

The above problem does not occur when i use my custom made deserializer. Here is a detailed stacktrace of the error. I dont know why it is trying to cast empty string to date.

```
Caused by: com.arangodb.velocypack.exception.VPackParserException: java.lang.NumberFormatException: For input string: ""
        at com.arangodb.velocypack.VPack.deserialize(VPack.java:332)
        at com.arangodb.internal.util.ArangoDeserializerImpl.deserialize(ArangoDeserializerImpl.java:55)
        ... 135 more
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:601)
        at java.lang.Long.parseLong(Long.java:631)
        at java.text.DigitList.getLong(DigitList.java:195)
        at java.text.DecimalFormat.parse(DecimalFormat.java:2051)
        at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:2162)
        at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1514)
        at java.text.DateFormat.parse(DateFormat.java:364)
        at com.arangodb.velocypack.internal.util.DateUtil.parse(DateUtil.java:55)
        at com.arangodb.velocypack.internal.VPackDeserializers$12.deserialize(VPackDeserializers.java:157)
        at com.arangodb.velocypack.internal.VPackDeserializers$12.deserialize(VPackDeserializers.java:148)
        at com.arangodb.velocypack.VPack.getValue(VPack.java:455)
        at com.arangodb.velocypack.VPack.deserializeField(VPack.java:433)
        at com.arangodb.velocypack.VPack.deserializeFields(VPack.java:421)
        at com.arangodb.velocypack.VPack.deserializeObject(VPack.java:372)
        at com.arangodb.velocypack.VPack.getValue(VPack.java:478)
        at com.arangodb.velocypack.VPack.deserialize(VPack.java:330)
        ... 136 more
```

**Comment by mpv1989** [comment]
very strange. I tried to reproduce this with your example date and it works for me.

Can you please test this code? It uses `DateUtil` which is used from the velocypack deserialiser.
```Java
final String source = "2017-04-07T13:49:58.450Z";
final Date date = com.arangodb.velocypack.internal.util.DateUtil.parse(source);
System.out.println(date);
```

It should prints: `Fri Apr 07 13:49:58 CEST 2017`

**Comment by grexe** [comment]
I see you closed this issue @mpv1989 - we will keep an eye on it and post updates when we can reproduce better.
We tried both sync and async driver and the issue sporadically appeared in both cases in a wildfly 10 deployment.
We use JDK8 Java Time API internally now and translate to Instant in our custom (de)serializer.

Seems that redeploys in Wildfly are the best way to trigger this error, which is not a production use case, but still bothers us a little...

**Comment by grexe** [comment]
PS: here's a full stack trace after redeploy:
```
12:30:53,499 ERROR [com.arangodb.internal.CollectionCache] (default task-35) java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.: com.arangodb.ArangoDBException: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.                                                                                                                                                                                                             

        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.arangodb.internal.velocystream.ConnectionSync.write(ConnectionSync.java:87)
        ... 155 more
Caused by: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
        at com.arangodb.internal.velocystream.MessageStore.get(MessageStore.java:73)
        at com.arangodb.internal.velocystream.ConnectionSync$1.call(ConnectionSync.java:81)
        at com.arangodb.internal.velocystream.ConnectionSync$1.call(ConnectionSync.java:78)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.arangodb.internal.velocystream.MessageStore.clear(MessageStore.java:96)
        at com.arangodb.internal.velocystream.Connection$1.call(Connection.java:154)
        at com.arangodb.internal.velocystream.Connection$1.call(Connection.java:134)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
Caused by: java.io.IOException: Reached the end of the stream.
        at com.arangodb.internal.velocystream.Connection.readBytesIntoBuffer(Connection.java:265)
        at com.arangodb.internal.velocystream.Connection.readBytes(Connection.java:257)
        at com.arangodb.internal.velocystream.Connection.readChunk(Connection.java:234)
        at com.arangodb.internal.velocystream.Connection$1.call(Connection.java:145)
        ... 5 more
```

**Comment by grexe** [comment]
short PS for others that may run into this: indeed we found that due to a forgotten refactoring/test, the DAO was injected wrongly using just plain CDI @Inject instead of @EJB. This solved the concurrency issues.

Regarding Date (de)serialization, we are now also making sure our own ObjectMapper is always used (was overshadowed by the spotify-docker-lib's own mapper) and so the Jackson Java8 DateTime mapper is correctly picked up, which solves Date mapping issues over our REST API, though we didn't try without the custom VPack serializer yet.
