### ISSUE TITLE
Null Pointer when JSON string is written to ArangoDB using Java Driver.

### ISSUE THREAD

**Issue by sanjuthomas** [arangodb/arangodb-java-driver#121]
This is happening intermittently for random JSON string.

The API used - 
arangoDB.db("db-name").collection("collection-name").insertDocument(JSON String);

JSON String in this case was -  {"symbol":"BABA","quantity":90,"client":{"id":"C9056","account":{"id":"A9056"}},"id":"Q9056","url":"/C9056/A9056/Q9056.json","timestamp":1493149458406} 

Java Driver Version - 4.1.10

[2017-04-27 20:24:43,240] INFO {"symbol":"BABA","quantity":90,"client":{"id":"C9056","account":{"id":"A9056"}},"id":"Q9056","url":"/C9056/A9056/Q9056.json","timestamp":1493149458406} (org.sanju.kafka.connect.arangodb.ArangoDBWriter:71)
[2017-04-27 20:24:43,242] INFO  (org.sanju.kafka.connect.arangodb.ArangoDBWriter:71)
[2017-04-27 20:24:43,244] ERROR Task arangodb-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:449)
java.lang.NullPointerException
	at com.arangodb.util.ArangoUtil.serialize(ArangoUtil.java:119)
	at com.arangodb.util.ArangoUtil.serialize(ArangoUtil.java:99)
	at com.arangodb.util.ArangoUtil.serialize(ArangoUtil.java:85)
	at com.arangodb.internal.ArangoExecutor.serialize(ArangoExecutor.java:140)
	at com.arangodb.internal.InternalArangoCollection.insertDocumentRequest(InternalArangoCollection.java:87)
	at com.arangodb.ArangoCollection.insertDocument(ArangoCollection.java:79)

**Comment by mpv1989** [comment]
I tried to reproduce your problem with your example document:
```
DocumentCreateEntity<String> res = arangoDB.db().collection("test").insertDocument(
			"{\"symbol\":\"BABA\",\"quantity\":90,\"client\":{\"id\":\"C9056\",\"account\":{\"id\":\"A9056\"}},\"id\":\"Q9056\",\"url\":\"/C9056/A9056/Q9056.json\",\"timestamp\":1493149458406}");
```
This works for me.

I can only reproduce the stacktrace of yours when I pass `null` to the method `insertDocument(Object)`. Are you sure your JSON String isn't null and is really pass to insertDocument(Object)?

**Comment by sanjuthomas** [comment]
please close this. I think the log wasn't ordered.
