### ISSUE TITLE
ArangoVertexCollection.getVertex throws VPackParserException: NumberFormatException

### ISSUE THREAD

**Issue by grumpy-programmer** [arangodb/arangodb-java-driver#139]
I have problem with `ArangoVertexCollection.getVertex` sometimes deserialize throws NumberFormatException (random vertices, random occurrence)

arangodb: 3.2.0
arangodb-java-driver: 4.2.1

`com.arangodb.ArangoDBException: com.arangodb.velocypack.exception.VPackParserException: java.lang.NumberFormatException:`
with following messages:
For input string: "E5"
multiple points
For input string: ""

Value of `VPackSlice vpack` argument in com.arangodb.internal.util.ArangoDeserializerImpl.deserialize(ArangoDeserializerImpl.java:59)

`{"_key":"fae8244dcf03c14cd22199b614606e0f","_id":"session\/fae8244dcf03c14cd22199b614606e0f","_rev":"_VWnEqCq---","base":false,"ended":false,"id":"efb9a4fb-c353-4dc0-82e0-605874028656","updatedAt":"2017-07-28T19:37:54.000Z","createdAt":"2017-07-28T05:00:05.000Z","firstSession":false}`

POJO:
```
@VertexCollection(collection = "session", keys = "id")
@Data
@Generated
@EqualsAndHashCode(callSuper = true)
public class SessionVertex extends CreateAwareVertex {

    private String id;

    private Date updatedAt;

    private Boolean firstSession;

    private Boolean ended = false;

    public SessionVertex() {
        setBase(false);
    }

    public SessionVertex(String id) {
        this.id = id;
        setBase(true);
    }
}

@Data
@Generated
@EqualsAndHashCode(callSuper = true)
public abstract class CreateAwareVertex extends Vertex {

    private Date createdAt;

    private Boolean base;

    public CreateAwareVertex() {
    }
}

@ToString(callSuper = true)
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
public abstract class Vertex extends Document {
}
```
@VertexCollection - annotation for my vertex repository
I'm using lombok

com.arangodb.ArangoDBException: com.arangodb.velocypack.exception.VPackParserException: java.lang.NumberFormatException: For input string: "E5"
	at com.arangodb.internal.util.ArangoDeserializerImpl.deserialize(ArangoDeserializerImpl.java:59)
	at com.arangodb.internal.util.ArangoUtilImpl.deserialize(ArangoUtilImpl.java:92)
	at com.arangodb.internal.InternalArangoVertexCollection$2.deserialize(InternalArangoVertexCollection.java:111)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:59)
	at com.arangodb.ArangoVertexCollection.getVertex(ArangoVertexCollection.java:105)
	at com.example.arango.repository.vertex.VertexRepositoryImpl.findOneByHashedKey(VertexRepositoryImpl.java:50)
	at com.example.arango.repository.vertex.VertexRepositoryImpl.findOneByHashedKey(VertexRepositoryImpl.java:13)
	at com.example.arango.repository.AbstractArangoRepository.findOrInsert(AbstractArangoRepository.java:53)
	at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:504)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:489)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:461)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy98.findOrInsert(Unknown Source)
	at com.example.nachi.service.session.SessionServiceImpl.getOrCreateDefault(SessionServiceImpl.java:50)
	at com.example.nachi.service.session.SessionServiceImpl.update(SessionServiceImpl.java:88)
	at com.example.nachi.controller.SessionController.onSessionUpdate(SessionController.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:180)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:112)
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:48)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
	at org.springframework.cloud.stream.binding.DispatchingStreamListenerMessageHandler$ConditionalStreamListenerHandler.handleMessage(DispatchingStreamListenerMessageHandler.java:122)
	at org.springframework.cloud.stream.binding.DispatchingStreamListenerMessageHandler.handleRequestMessage(DispatchingStreamListenerMessageHandler.java:75)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:148)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:121)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:89)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:423)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:373)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:292)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:212)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:129)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:115)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
	at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:70)
	at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:64)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:171)
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$400(AmqpInboundChannelAdapter.java:45)
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$1.onMessage(AmqpInboundChannelAdapter.java:95)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:783)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:706)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer.java:96)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$1.invokeListener(SimpleMessageListenerContainer.java:187)
	at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:91)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:286)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:179)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:115)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy146.invokeListener(Unknown Source)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.invokeListener(SimpleMessageListenerContainer.java:1274)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:687)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:1217)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:1187)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:96)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1414)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.arangodb.velocypack.exception.VPackParserException: java.lang.NumberFormatException: For input string: "E5"
	at com.arangodb.velocypack.VPack.deserialize(VPack.java:398)
	at com.arangodb.internal.util.ArangoDeserializerImpl.deserialize(ArangoDeserializerImpl.java:55)
	... 84 common frames omitted
Caused by: java.lang.NumberFormatException: For input string: "E5"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at java.text.DigitList.getLong(DigitList.java:195)
	at java.text.DecimalFormat.parse(DecimalFormat.java:2051)
	at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:2162)
	at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1514)
	at java.text.DateFormat.parse(DateFormat.java:364)
	at com.arangodb.velocypack.internal.util.DateUtil.parse(DateUtil.java:55)
	at com.arangodb.velocypack.internal.VPackDeserializers$12.deserialize(VPackDeserializers.java:157)
	at com.arangodb.velocypack.internal.VPackDeserializers$12.deserialize(VPackDeserializers.java:148)
	at com.arangodb.velocypack.VPack.getValue(VPack.java:546)
	at com.arangodb.velocypack.VPack.deserializeField(VPack.java:512)
	at com.arangodb.velocypack.VPack.deserializeFields(VPack.java:500)
	at com.arangodb.velocypack.VPack.deserializeObject(VPack.java:451)
	at com.arangodb.velocypack.VPack.getValue(VPack.java:569)
	at com.arangodb.velocypack.VPack.deserialize(VPack.java:396)
	... 85 common frames omitted

**Comment by mpv1989** [comment]
@grumpy-programmer thanks for reporting.

This was a bug with `SimpleDateFormat`. I forgot to handle that it isn't thread-safe.
I released a new driver version (4.2.3).
