### ISSUE TITLE
ArangoDBException cause CUP 100%

### ISSUE THREAD

**Issue by EhsanTang** [arangodb/arangodb-java-driver#171]
arangodb-java-driver: 4.3.1
arangodb: 3.2.6

`InputStream in = VertexUserDao.class.getResourceAsStream("arangodb.properties");
            arangoDB = new ArangoDB.Builder().loadProperties(in).loadBalancingStrategy(LoadBalancingStrategy.ROUND_ROBIN).acquireHostList(true).build();`

**Sometimes the arangodb cup up to 100%. After i restart the project(not the db server), the db server will be right in few minutes. I think the problem cause by  connection pool**

`com.arangodb.ArangoDBException: Response: 501, Error: 9 - '' not implemented
	at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:53) ~[arangodb-java-driver-4.3.1.jar!/:?]
	at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:116) ~[arangodb-java-driver-4.3.1.jar!/:?]
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:143) ~[arangodb-java-driver-4.3.1.jar!/:?]
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:48) ~[arangodb-java-driver-4.3.1.jar!/:?]
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:100) ~[arangodb-java-driver-4.3.1.jar!/:?]
	at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:47) ~[arangodb-java-driver-4.3.1.jar!/:?]
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71) ~[arangodb-java-driver-4.3.1.jar!/:?]
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:63) ~[arangodb-java-driver-4.3.1.jar!/:?]
	at com.arangodb.ArangoVertexCollection.updateVertex(ArangoVertexCollection.java:192) ~[arangodb-java-driver-4.3.1.jar!/:?]
	at com.lagou.mds.pandora.core.dao.vertex.VertexUserDao.update(VertexUserDao.java:57) ~[mds-pandora-core-0.0.1.jar!/:0.0.1]
	at com.lagou.mds.pandora.service.vertex.VertexUserService.updateDesireByEvent(VertexUserService.java:394) ~[classes!/:0.0.1]
	at com.lagou.mds.pandora.kafka.consumer.MdsUpdateResumeConsumer.consumeHandle(MdsUpdateResumeConsumer.java:98) ~[classes!/:0.0.1]
	at com.lagou.mds.pandora.kafka.consumer.MdsUpdateResumeConsumer.consumeHandle(MdsUpdateResumeConsumer.java:32) ~[classes!/:0.0.1]
	at com.lagou.mds.pandora.kafka.consumer.AbstractPandoraConsumer.consume(AbstractPandoraConsumer.java:45) [classes!/:0.0.1]
	at com.lagou.common.message.support.AbstractMessageListenerChannel.doConsume(AbstractMessageListenerChannel.java:57) [lagou-common-message-core-0.0.3.jar!/:?]
	at com.lagou.common.message.kafka.KafkaMessageListenerChannel.access$1(KafkaMessageListenerChannel.java:1) [lagou-common-message-kafka-0.0.3.jar!/:?]
	at com.lagou.common.message.kafka.KafkaMessageListenerChannel$SingleKafkaTask$1.run(KafkaMessageListenerChannel.java:143) [lagou-common-message-kafka-0.0.3.jar!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
`

**Comment by mpv1989** [comment]
We released version `4.3.7` of the driver, where we changed some thing in the connection pool. Can you test this version please?

**Comment by mpv1989** [comment]
I will close this issue. Feel free to open it again if your problem is still not solved
