### ISSUE TITLE
Edge import does not work with Arango cluster

### ISSUE THREAD

**Issue by gabata** [arangodb/arangodb-java-driver#173]
Arango Java Driver could not import edge documents with cluster configuration. The log messages says that it could not connect to host, however importing to document type collections works without any issues. Inserting edges works as well.

*System Details:*
* Operating system: Windows 10
* Arango package: ArangoDB3-3.3.3-1_win64.zip
* arangodb-java-driver: 4.3.3

*Steps to reproduce:*
1. I have started an ArangoDB cluster locally using the arango starter: `arangodb --starter.local`
2. Created an ArangoDatabase instance with
```java
    ArangoDatabase db = new ArangoDB.Builder()
        .host("localhost", 8529)
        .user("root")
        .password("")
        .useProtocol(Protocol.HTTP_VPACK) // tried VST, HTTP_JSON as well
        .acquireHostList(Boolean.TRUE)
        .loadBalancingStrategy(LoadBalancingStrategy.ROUND_ROBIN)
        .build()
        .db(databaseName);
    }
```

3. Created edge collection with the following code
```java
    public CollectionEntity createEdgeCollection(String edgeCollectionName, String nodeCollectionName) {
        CollectionCreateOptions options = new CollectionCreateOptions();
        options.type(CollectionType.EDGES);
        options.shardKeys("vertex");
        CollectionPropertiesEntity properties = db.collection(nodeCollectionName).getProperties();
        options.replicationFactor(properties.getReplicationFactor()); // 2
        options.numberOfShards(properties.getNumberOfShards()); // 9
        options.indexBuckets(indexBuckets); // 64
        // as per: https://docs.arangodb.com/3.3/Manual/Graphs/Pregel/
        options.distributeShardsLike(nodeCollectionName);
        return db.createCollection(edgeCollectionName, options);
    }
```

4. Called the import

```java
    public DocumentImportEntity save(Collection<Edge> edges, String nodeCollectionName, String edgeCollectionName) {
        DocumentImportOptions importOptions = new DocumentImportOptions();
        importOptions.onDuplicate(ON_DUPLICATE_ACTION); // ignore
        importOptions.waitForSync(Boolean.TRUE);
        importOptions.fromPrefix(nodeCollectionName);
        importOptions.toPrefix(nodeCollectionName);
        return db.collection(edgeCollectionName).importDocuments(edges, importOptions);
    }
```

5. Errors from the logs
```
com.arangodb.internal.http.HttpCommunication WARN Could not connect to host[addr=localhost,port=8534]. Try connecting to host[addr=localhost,port=8539]
com.arangodb.internal.http.HttpCommunication WARN Could not connect to host[addr=localhost,port=8539]. Try connecting to host[addr=localhost,port=8529]
com.arangodb.internal.http.HttpCommunication WARN Could not connect to host[addr=localhost,port=8529]. Try connecting to host[addr=localhost,port=8534]

com.arangodb.ArangoDBException: Response Code: 503
        at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:55) ~[arangodb-java-driver-4.3.3.jar!/:?]
        at com.arangodb.internal.http.HttpConnection.checkError(HttpConnection.java:340) ~[arangodb-java-driver-4.3.3.jar!/:?]
        at com.arangodb.internal.http.HttpConnection.execute(HttpConnection.java:204) ~[arangodb-java-driver-4.3.3.jar!/:?]
        at com.arangodb.internal.http.HttpCommunication.execute(HttpCommunication.java:144) ~[arangodb-java-driver-4.3.3.jar!/:?]
        at com.arangodb.internal.http.HttpCommunication.execute(HttpCommunication.java:129) ~[arangodb-java-driver-4.3.3.jar!/:?]
        at com.arangodb.internal.http.HttpProtocol.execute(HttpProtocol.java:49) ~[arangodb-java-driver-4.3.3.jar!/:?]
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71) ~[arangodb-java-driver-4.3.3.jar!/:?]
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:53) ~[arangodb-java-driver-4.3.3.jar!/:?]
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:49) ~[arangodb-java-driver-4.3.3.jar!/:?]
        at com.arangodb.ArangoCollection.importDocuments(ArangoCollection.java:167) ~[arangodb-java-driver-4.3.3.jar!/:?]
```

**Comment by mpv1989** [comment]
@gabata Hi,

I was not able to reproduce your problem. Are you able to provide me the log output of your coordinators in your cluster?

**Comment by gabata** [comment]
Sorry for my late answer @mpv1989 , the loug output of the coordinators are:

coordinator8529:
```
2018-02-27T10:37:44Z [12796] INFO ArangoDB 3.3.3 [win64] 64bit, using VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2a 19 Mar 2015
2018-02-27T10:37:44Z [12796] INFO using storage engine mmfiles
2018-02-27T10:37:44Z [12796] INFO {cluster} Starting up with role COORDINATOR
2018-02-27T10:37:52Z [12796] INFO {cluster} Fresh start. Persisting new UUID CRDN-877b5e3a-e750-4bed-a673-2967001befc6
2018-02-27T10:37:52Z [12796] INFO {cluster} Waiting for DBservers to show up...
2018-02-27T10:37:52Z [12796] INFO {cluster} Found 2 DBservers.
2018-02-27T10:37:52Z [12796] INFO {authentication} Authentication is turned on (system only)
2018-02-27T10:37:52Z [12796] INFO created base application directory 'C:\arango1\usr\bin\coordinator8529\apps\_db'
2018-02-27T10:37:52Z [12796] INFO WAL directory 'C:/arango1/usr/bin/coordinator8529/data\journals' does not exist. creating it...
2018-02-27T10:37:53Z [12796] INFO {cluster} Cluster feature is turned on. Agency version: {"server":"arango","version":"3.3.3","license":"community"}, Agency endpoints: http+tcp://127.0.0.1:8531, http+tcp://127.0.0.1:8541, http+tcp://127.0.0.1:8536, server id: 'CRDN-877b5e3a-e750-4bed-a673-2967001befc6', internal address: tcp://localhost:8529, role: COORDINATOR
2018-02-27T10:37:53Z [12796] INFO {cluster} using heartbeat interval value '1000 ms' from agency
2018-02-27T10:37:53Z [12796] INFO using endpoint 'http+tcp://[::]:8529' for non-encrypted requests
2018-02-27T10:38:08Z [12796] INFO Waiting for initial replication of system collections...
2018-02-27T10:38:08Z [12796] INFO bootstrapped coordinator CRDN-877b5e3a-e750-4bed-a673-2967001befc6
2018-02-27T10:38:08Z [12796] INFO ArangoDB (version 3.3.3 [win64]) is ready for business. Have fun!
2018-02-27T10:38:38Z [10580] INFO ArangoDB 3.3.3 [win64] 64bit, using VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2a 19 Mar 2015
2018-02-27T10:38:38Z [10580] INFO using storage engine mmfiles
2018-02-27T10:38:38Z [10580] INFO {cluster} Starting up with role COORDINATOR
2018-02-27T10:38:38Z [10580] INFO {cluster} Waiting for DBservers to show up...
2018-02-27T10:38:38Z [10580] INFO {cluster} Found 3 DBservers.
2018-02-27T10:38:38Z [10580] INFO {authentication} Authentication is turned on (system only)
2018-02-27T10:38:38Z [10580] INFO {cluster} Cluster feature is turned on. Agency version: {"server":"arango","version":"3.3.3","license":"community"}, Agency endpoints: http+tcp://127.0.0.1:8531, http+tcp://127.0.0.1:8536, http+tcp://127.0.0.1:8541, server id: 'CRDN-877b5e3a-e750-4bed-a673-2967001befc6', internal address: tcp://localhost:8529, role: COORDINATOR
2018-02-27T10:38:38Z [10580] INFO {cluster} using heartbeat interval value '1000 ms' from agency
2018-02-27T10:38:38Z [10580] INFO using endpoint 'http+tcp://[::]:8529' for non-encrypted requests
2018-02-27T10:38:39Z [10580] INFO bootstrapped coordinator CRDN-877b5e3a-e750-4bed-a673-2967001befc6
2018-02-27T10:38:39Z [10580] INFO ArangoDB (version 3.3.3 [win64]) is ready for business. Have fun!
```

local-slave-1/coordinator8534:
```
2018-02-27T10:37:44Z [7472] INFO ArangoDB 3.3.3 [win64] 64bit, using VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2a 19 Mar 2015
2018-02-27T10:37:44Z [7472] INFO using storage engine mmfiles
2018-02-27T10:37:44Z [7472] INFO {cluster} Starting up with role COORDINATOR
2018-02-27T10:37:51Z [7472] INFO {cluster} Fresh start. Persisting new UUID CRDN-d40bd233-b677-4841-977f-20eff1f73a28
2018-02-27T10:37:51Z [7472] INFO {cluster} Waiting for DBservers to show up...
2018-02-27T10:37:52Z [7472] INFO {cluster} Waiting for DBservers to show up...
2018-02-27T10:37:52Z [7472] INFO {cluster} Found 2 DBservers.
2018-02-27T10:37:52Z [7472] INFO {authentication} Authentication is turned on (system only)
2018-02-27T10:37:52Z [7472] INFO created base application directory 'C:\arango1\usr\bin\local-slave-1\coordinator8534\apps\_db'
2018-02-27T10:37:52Z [7472] INFO WAL directory 'C:/arango1/usr/bin/local-slave-1/coordinator8534/data\journals' does not exist. creating it...
2018-02-27T10:37:53Z [7472] INFO {cluster} Cluster feature is turned on. Agency version: {"server":"arango","version":"3.3.3","license":"community"}, Agency endpoints: http+tcp://127.0.0.1:8531, http+tcp://127.0.0.1:8541, http+tcp://127.0.0.1:8536, server id: 'CRDN-d40bd233-b677-4841-977f-20eff1f73a28', internal address: tcp://localhost:8534, role: COORDINATOR
2018-02-27T10:37:53Z [7472] INFO {cluster} using heartbeat interval value '1000 ms' from agency
2018-02-27T10:37:53Z [7472] INFO using endpoint 'http+tcp://[::]:8534' for non-encrypted requests
2018-02-27T10:38:09Z [7472] INFO bootstrapped coordinator CRDN-d40bd233-b677-4841-977f-20eff1f73a28
2018-02-27T10:38:09Z [7472] INFO ArangoDB (version 3.3.3 [win64]) is ready for business. Have fun!
```

local-slave-2/coordinator8539:
```
2018-02-27T10:37:42Z [7308] INFO ArangoDB 3.3.3 [win64] 64bit, using VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2a 19 Mar 2015
2018-02-27T10:37:42Z [7308] INFO using storage engine mmfiles
2018-02-27T10:37:42Z [7308] INFO {cluster} Starting up with role COORDINATOR
2018-02-27T10:37:52Z [7308] INFO {cluster} Fresh start. Persisting new UUID CRDN-a6bd9275-fbdb-4a5b-81fe-c951fed04841
2018-02-27T10:37:53Z [7308] INFO {cluster} Waiting for DBservers to show up...
2018-02-27T10:37:53Z [7308] INFO {cluster} Found 3 DBservers.
2018-02-27T10:37:53Z [7308] INFO {authentication} Authentication is turned on (system only)
2018-02-27T10:37:53Z [7308] INFO created base application directory 'C:\arango1\usr\bin\local-slave-2\coordinator8539\apps\_db'
2018-02-27T10:37:53Z [7308] INFO WAL directory 'C:/arango1/usr/bin/local-slave-2/coordinator8539/data\journals' does not exist. creating it...
2018-02-27T10:37:54Z [7308] INFO {cluster} Cluster feature is turned on. Agency version: {"server":"arango","version":"3.3.3","license":"community"}, Agency endpoints: http+tcp://127.0.0.1:8531, http+tcp://127.0.0.1:8541, http+tcp://127.0.0.1:8536, server id: 'CRDN-a6bd9275-fbdb-4a5b-81fe-c951fed04841', internal address: tcp://localhost:8539, role: COORDINATOR
2018-02-27T10:37:54Z [7308] INFO {cluster} using heartbeat interval value '1000 ms' from agency
2018-02-27T10:37:55Z [7308] INFO using endpoint 'http+tcp://[::]:8539' for non-encrypted requests
2018-02-27T10:38:09Z [7308] INFO bootstrapped coordinator CRDN-a6bd9275-fbdb-4a5b-81fe-c951fed04841
2018-02-27T10:38:09Z [7308] INFO ArangoDB (version 3.3.3 [win64]) is ready for business. Have fun!
```

---

I have also included a Groovy script which can be used to reproduce the issue:

```groovy
@Grab(group='org.apache.httpcomponents', module='httpclient', version='4.5.1')
@Grab(group='org.slf4j', module='slf4j-api', version='1.7.25')
@Grab(group='com.arangodb', module='arangodb-java-driver', version='4.3.3')
import com.arangodb.ArangoDB
import com.arangodb.ArangoDatabase
import com.arangodb.entity.DocumentField
import com.arangodb.entity.DocumentField.Type
import com.arangodb.model.CollectionCreateOptions
import com.arangodb.entity.CollectionType
import com.arangodb.model.GraphCreateOptions
import com.arangodb.entity.EdgeDefinition
import com.arangodb.model.DocumentImportOptions
import com.arangodb.model.DocumentImportOptions.OnDuplicate
import com.arangodb.Protocol

databaseName = "random"
arango = new ArangoDB.Builder().host("localhost", 8529).user("root").password("").useProtocol(Protocol.HTTP_VPACK).build()
db = arango.db(databaseName)
nodeSize = 1_000
random = new Random(1)
types = ["TYPE1", "TYPE2", "TYPE3", "TYPE4"]
nodeImportOptions = new DocumentImportOptions().waitForSync(Boolean.TRUE).onDuplicate(OnDuplicate.update)
edgeImportOptions = new DocumentImportOptions().waitForSync(Boolean.TRUE).onDuplicate(OnDuplicate.ignore)
replicationFactor = 2
numberOfShards = 9
indexBuckets = 64

class Node {
    @DocumentField(Type.ID) String id
    @DocumentField(Type.KEY) String key
    List<String> ids
    String type
    Date modificationDate

    Node(ids, type) {
        ids = ids.sort().collect()
        this.type = type
        key = "${type}.${ids.sort().join('.')}"
        modificationDate = new Date()
    }
}

class Edge {
    @DocumentField(Type.ID) String uid
    @DocumentField(Type.KEY) String key
    @DocumentField(Type.FROM) String sourceId
    @DocumentField(Type.TO) String destinationId
    String vertex

    Edge(vertexCollection, sourceKey, destinationKey) {
        sourceId = "${vertexCollection}/${sourceKey}"
        destinationId = "${vertexCollection}/${destinationKey}"
        vertex = sourceKey
        key = "${sourceKey}:${destinationKey}"
    }
}

def createNodeCollection(name) {
    if (!db.collection(name).exists()) {
        println "Create ${name}..."
        def options = new CollectionCreateOptions()
            .type(CollectionType.DOCUMENT)
            .shardKeys("_key")
            .replicationFactor(replicationFactor)
            .numberOfShards(numberOfShards)
            .indexBuckets(indexBuckets)
        db.createCollection(name, options)
    }
}

def createEdgeCollection(name, nodeCollection) {
    if (!db.collection(name).exists()) {
        println "Create ${name}..."
        def options = new CollectionCreateOptions()
            .type(CollectionType.EDGES)
            .shardKeys("vertex")
            .distributeShardsLike(nodeCollection)
            .replicationFactor(replicationFactor)
            .numberOfShards(numberOfShards)
            .indexBuckets(indexBuckets)
        db.createCollection(name, options)
    }
}

def createGraph(name, nodeCollection, edgeCollections) {
    if (!db.graph(name).exists()) {
        println "Create ${name}..."
        def options = new GraphCreateOptions()
            .replicationFactor(replicationFactor)
            .numberOfShards(numberOfShards)
        def edgeDefinitions = edgeCollections.collect { new EdgeDefinition().collection(it).from(nodeCollection).to(nodeCollection) }
        db.createGraph(name, edgeDefinitions, options)
    }
}

if (!db.exists()) {
    arango.createDatabase(databaseName)
}

[123, 456].each { id ->
    def nodeCollection = "node-${id}"
    def edgeCollection = "relation-${id}"
    def graph = "graph-${id}"
    def edges = []

    createNodeCollection(nodeCollection)
    createEdgeCollection(edgeCollection, nodeCollection)
    createGraph(graph, nodeCollection, [edgeCollection])

    println "Import nodes to ${nodeCollection}..."
    nodes = (1 .. nodeSize).collect { new Node([it], types[random.nextInt(types.size())]) }
    db.collection(nodeCollection).importDocuments(nodes, nodeImportOptions)

    println "Import edges to ${edgeCollection}..."
    edges = []
    nodes.each { node ->
        def index = random.nextInt(nodeSize)
        if (nodes[index].key != node.key) { edges.add(new Edge(nodeCollection, node.key, nodes[index].key)) }
    }
    db.collection(edgeCollection).importDocuments(edges, edgeImportOptions)
}

println "Disconnect..."
arango.shutdown()
```

Whicj result in the following:

```
Create node-123...
Create relation-123...
Create graph-123...
Import nodes to node-123...
Import edges to relation-123...
Caught: com.arangodb.ArangoDBException: Response Code: 503
com.arangodb.ArangoDBException: Response Code: 503
        at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:55)
        at com.arangodb.internal.http.HttpConnection.checkError(HttpConnection.java:340)
        at com.arangodb.internal.http.HttpConnection.execute(HttpConnection.java:204)
        at com.arangodb.internal.http.HttpCommunication.execute(HttpCommunication.java:144)
        at com.arangodb.internal.http.HttpCommunication.execute(HttpCommunication.java:129)
        at com.arangodb.internal.http.HttpProtocol.execute(HttpProtocol.java:49)
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:53)
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:49)
        at com.arangodb.ArangoCollection.importDocuments(ArangoCollection.java:167)
        at com.arangodb.ArangoCollection$importDocuments$0.call(Unknown Source)
        at arango-random-data$_run_closure1.doCall(arango-random-data.groovy:120)
        at arango-random-data.run(arango-random-data.groovy:100)
```

**Comment by gabata** [comment]
Ok, I got a more detailed error response with using `db.graph(graph).edgeCollection(edgeCollection).insertEdge(edge)`

```
com.arangodb.ArangoDBException: Response: 410, Error: 1906 - must not specify _key for this collection
```

This is definitely not an issue with the Java Driver itself, so I'm closing this issue. As per https://groups.google.com/forum/#!topic/arangodb/x5d7q8O8Hew

> If you use any other attribute than _key as the shard key attribute, you
> cannot use user-defined keys anymore. The database will determine the
> _key value for you in this case. However, you can of course define the
> values for the sharding attributes then.
