### ISSUE TITLE
It should be possible to assign a primary key value explicitly (currently causes: com.arangodb.ArangoDBException: Response: 404, Error: 1202 - document not found)

### ISSUE THREAD

**Issue by haqer1** [arangodb/arangodb-java-driver#183]
For some entities, there is a real-world natural id, & it can be advantageous to assign & use it directly, rather than using an auto-generated id. Among advantages are: more descriptive records, using less disk space (by virtue of using 1 column less per record
).
However, at present, doing so is impossible resulting in an exception[1].

I've tried 2 approaches for explicitly-assigned IDs:
1) real-world-key
2) DocumentName/real-world-key
Both are impossible, & cause the afore-mentioned exception.

Thus, for now one has to use an auto-generated ID.

P.S. 
[1] org.springframework.dao.InvalidDataAccessResourceUsageException: Response: 404, Error: 1202 - document not found; nested exception is com.arangodb.ArangoDBException: Response: 404, Error: 1202 - document not found
	at com.arangodb.springframework.core.util.ArangoExceptionTranslator.translateExceptionIfPossible(ArangoExceptionTranslator.java:58)
	at com.arangodb.springframework.core.template.ArangoTemplate.translateExceptionIfPossible(ArangoTemplate.java:134)
	at com.arangodb.springframework.core.template.ArangoTemplate.update(ArangoTemplate.java:393)
	at com.arangodb.springframework.core.template.ArangoTemplate.update(ArangoTemplate.java:399)
	at com.arangodb.springframework.core.template.ArangoTemplate.upsert(ArangoTemplate.java:532)
	at com.arangodb.springframework.repository.SimpleArangoRepository.save(SimpleArangoRepository.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
Caused by: com.arangodb.ArangoDBException: Response: 404, Error: 1202 - document not found
	at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:53)
	at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:116)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:143)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:48)
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:100)
	at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:47)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:63)
	at com.arangodb.ArangoCollection.updateDocument(ArangoCollection.java:365)
	at com.arangodb.springframework.core.template.ArangoTemplate.update(ArangoTemplate.java:388)
	... 76 more

**Comment by Queatz** [comment]
This is possible.  What is the query or method you are using?

**Comment by dothebart** [comment]
it is at least possible to some extend. There are some restrictions: https://docs.arangodb.com/3.3/Manual/DataModeling/NamingConventions/DocumentKeys.html
If you need more complex strings you should i.e. base64 encode the string.

**Comment by mpv1989** [comment]
Is this problem solved? I will close this issue, feel free to open it again if additional help is needed.
