### ISSUE TITLE
Cannot use connection object once the Arango restarts.

### ISSUE THREAD

**Issue by Himansu-Nayak** [arangodb/arangodb-java-driver#186]
We use arangodb-java-driver::4.2.3 driver on our spring boot application. And we see the below issue frequently whenever database(arango(ver 3.1.21, bug fix ver 3.1.28) goes down and comes up. Any further writing to database failed with the below message and only a restart of the application help us to write further. 

version of arango: **ver 3.1.21, bug fix ver 3.1.28**
version of arangodb-java-driver: **4.2.3**
arangodb connection snippet: 

_Arango arangoDB = new ArangoDB.Builder()
                .host(host, port)
                .user(user)
                .password(password)
                .registerInstanceCreator(TimeZone.class, new TimeZoneInstanceCreator())
                .build();_

**Exception:**

**com.arangodb.ArangoDBException: java.net.SocketException: Broken pipe (Write failed)**
                at com.arangodb.internal.velocystream.internal.**Connection.writeIntern(Connection.java:216)**
                at com.arangodb.internal.velocystream.internal.ConnectionSync.write(ConnectionSync.java:86)
                at com.arangodb.internal.velocystream.VstCommunicationSync.send(VstCommunicationSync.java:147)
                at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:131)
                at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:46)
                at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:96)
                at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:46)
                at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:58)
                at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:47)
                at com.arangodb.ArangoDatabase.query(ArangoDatabase.java:343)

**Comment by gabata** [comment]
We are suffering from the same issue, after ArangoDB restarts we get the following exception:
```
com.arangodb.ArangoDBException: Was not able to connect to any host
  at com.arangodb.internal.http.HttpConnection.execute(HttpConnection.java:190) ~[arangodb-java-driver-4.3.5.jar!/:?]
  at com.arangodb.internal.http.HttpCommunication.execute(HttpCommunication.java:144) ~[arangodb-java-driver-4.3.5.jar!/:?]
  at com.arangodb.internal.http.HttpCommunication.execute(HttpCommunication.java:129) ~[arangodb-java-driver-4.3.5.jar!/:?]
  at com.arangodb.internal.http.HttpProtocol.execute(HttpProtocol.java:49) ~[arangodb-java-driver-4.3.5.jar!/:?]
  at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71) ~[arangodb-java-driver-4.3.5.jar!/:?]
  at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:53) ~[arangodb-java-driver-4.3.5.jar!/:?]
  at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:49) ~[arangodb-java-driver-4.3.5.jar!/:?]
  at com.arangodb.ArangoCollection.importDocuments(ArangoCollection.java:167) ~[arangodb-java-driver-4.3.5.jar!/:?]
```

We are building the connection with:
```java
ArangoDB.Builder builder = new ArangoDB.Builder()
  .user(arangoHostInfo.getUser())
  .password(arangoHostInfo.getPassword())
  .useProtocol(Protocol.HTTP_VPACK);
  .host(host, arangoHostInfo.getPort());
```

**Comment by mpv1989** [comment]
@gabata I'll probably implement the requested feature #141 next week. I'll look at your case in this turn.

**Comment by gabata** [comment]
Thanks @mpv1989 for fixing the issue. I have checked the implementation with the following groovy script and it seems the issue still persists:

```groovy
@Grab(group='org.slf4j', module='slf4j-api', version='1.7.25')
@Grab(group='org.slf4j', module='slf4j-simple', version='1.7.25')
@Grab(group='com.arangodb', module='arangodb-java-driver', version='4.3.6')
import com.arangodb.ArangoDB
import com.arangodb.ArangoDatabase
import com.arangodb.model.CollectionCreateOptions
import com.arangodb.entity.BaseDocument
import com.arangodb.entity.CollectionType
import com.arangodb.model.DocumentImportOptions
import com.arangodb.model.DocumentImportOptions.OnDuplicate
import com.arangodb.Protocol

def arango = new ArangoDB.Builder().host("localhost", 8529).user("root").password("").useProtocol(Protocol.VST).connectionTtl(1000).build()
def documentImportOptions = new DocumentImportOptions().waitForSync(Boolean.FALSE).onDuplicate(OnDuplicate.update)
def collectionCreateOptions = new CollectionCreateOptions().type(CollectionType.DOCUMENT)

def random = new Random(1)
def collectionName = "random"
def databaseName = "test"

try {
    if (!arango.db(databaseName).exists()) {
        arango.createDatabase(databaseName)
    }
} catch (Exception e) {
    println "Could not create database: ${e.getMessage()}"
}

if (!arango.db(databaseName).collection(collectionName).exists()) {
    println "Create ${collectionName}..."
    try {
        arango.db(databaseName).createCollection(collectionName, collectionCreateOptions)
    } catch (Exception e) {
        println "Could not create node collection: ${e.getMessage()}"
    }
}

while (true) {
    // restart AangoDB server during the import
    try {
        def document = new BaseDocument(["_key": random.nextInt(1000), "random": random.nextInt(1000)])
        println "Import document: ${document.toString()}"
        arango.db(databaseName).collection(collectionName).importDocuments([document], documentImportOptions)
    } catch (Exception e) {
        println "Could not import document: ${e.getMessage()}"
    }
    Thread.sleep(1000)
}

println "Disconnect..."
arango.shutdown()
```

Output:
```
Import document: BaseDocument [documentRevision=null, documentHandle=null, documentKey=317, properties={random=263}]
[main] ERROR com.arangodb.internal.velocystream.VstCommunication - Connection refused: connect
java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at com.arangodb.internal.velocystream.internal.VstConnection.open(VstConnection.java:121)
        at com.arangodb.internal.velocystream.VstCommunication.connect(VstCommunication.java:80)
        at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:143)
        at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:48)
        at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:100)
        at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:47)
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:53)
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:49)
        at com.arangodb.ArangoCollection.importDocuments(ArangoCollection.java:167)
        at com.arangodb.ArangoCollection$importDocuments$0.call(Unknown Source)
        at arango-reconnect.run(arango-reconnect.groovy:44)
        at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)
        at groovy.lang.GroovyShell.run(GroovyShell.java:518)
        at groovy.lang.GroovyShell.run(GroovyShell.java:507)
        at groovy.ui.GroovyMain.processOnce(GroovyMain.java:653)
        at groovy.ui.GroovyMain.run(GroovyMain.java:384)
        at groovy.ui.GroovyMain.process(GroovyMain.java:370)
        at groovy.ui.GroovyMain.processArgs(GroovyMain.java:129)
        at groovy.ui.GroovyMain.main(GroovyMain.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:109)
        at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)
Could not import document: java.net.ConnectException: Connection refused: connect
Import document: BaseDocument [documentRevision=null, documentHandle=null, documentKey=562, properties={random=234}]
Could not import document: Was not able to connect to any host
```

**Comment by gabata** [comment]
Thanks a lot @mpv1989 I have verified that the issue has been fixed.
Gabor
