### ISSUE TITLE
Repeated creation and use of DBConnections leads to Server Crash

### ISSUE THREAD

**Issue by gbjbaaha** [arangodb/arangodb-java-driver#189]
**Environment**
Testing with Driver version 4.3.5.
JDK = Oracle jdk1.8.0_144
Server version 3.3.7 (Running Docker image from https://hub.docker.com/r/arangodb/arangodb/)
Storage Engine = RocksDB
Docker version 18.03.0-ce-mac60 (23751) Stable on OSX 10.13.4

**Failure Scenario**
I realise that this test scenario is sub-optimal, but there is clearly a problem when creating database connections in a loop rather than creating a single instance and re-using the same connection pool. So I believe there are two distinct but related issues:-
1. Creating a new ArangoDatabase object and executing a query in a loop results in an exception in the client driver after around 984 loops (appears to be constant in my tests using a variety of queries and collections of test data)
2. Repeated runs of this test eventually causes the ArangoDB server instance and entire Docker daemon to crash.

My main concern is that a badly written piece of Java client code could cause a total server failure.

**Further Info**
The failure only occurs when running the driver in VST protocol. HTTP_JSON and HTTP_VPACK work successfully.
**Test Details**
Here is a simple JUnit test. You can run this against any collection, just modify the AQL accordingly.

```
@Test
   public void testReadSpecification() throws IOException
    {
        for(int i=0; i<10000; i++)
        {
            System.out.println("Loop #" + i);
            ArangoDatabase dbCon = new ArangoDB.Builder()
                    .host("localhost", 8529)
                    .user(dbUser)
                    .password(dbSecret)
                    .maxConnections(1)
                    .build().db(dbDatabase);

            List<String> results = new ArrayList<>();
            String aql = "FOR s in configs" +
                    "     RETURN s";

            ArangoCursor<String> cursor = dbCon.query(aql, null, null, String.class);

            while (cursor.hasNext())
            {
                System.out.println(cursor.next());
            }

            cursor.close();
        }
    }
````

At loop 984 (in my test case) the client throws a "Reached the end of the stream" Exception.
Moving the creation of the ArangoDatabase object to the outside of the loop (hence re-using the connection object) allows the test to run successfully. 

Here is the stacktrace from the test:-
````
Apr 17, 2018 10:58:04 AM com.arangodb.internal.velocystream.internal.MessageStore clear
SEVERE: Reached the end of the stream.
java.io.IOException: Reached the end of the stream.
	at com.arangodb.internal.velocystream.internal.VstConnection.readBytesIntoBuffer(VstConnection.java:289)
	at com.arangodb.internal.velocystream.internal.VstConnection.readBytes(VstConnection.java:281)
	at com.arangodb.internal.velocystream.internal.VstConnection.readChunk(VstConnection.java:258)
	at com.arangodb.internal.velocystream.internal.VstConnection$1.call(VstConnection.java:162)
	at com.arangodb.internal.velocystream.internal.VstConnection$1.call(VstConnection.java:151)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


com.arangodb.ArangoDBException: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.

	at com.arangodb.internal.velocystream.internal.ConnectionSync.write(ConnectionSync.java:97)
	at com.arangodb.internal.velocystream.VstCommunicationSync.send(VstCommunicationSync.java:155)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:140)
	at com.arangodb.internal.velocystream.VstCommunicationSync.authenticate(VstCommunicationSync.java:160)
	at com.arangodb.internal.velocystream.VstCommunicationSync.authenticate(VstCommunicationSync.java:48)
	at com.arangodb.internal.velocystream.VstCommunication.connect(VstCommunication.java:82)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:137)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:48)
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:100)
	at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:47)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:53)
	at com.arangodb.ArangoDatabase.query(ArangoDatabase.java:359)
	at com.synalogik.specification.microservice.TestArangoDB.testReadSpecification(TestArangoDB.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.arangodb.internal.velocystream.internal.ConnectionSync.write(ConnectionSync.java:93)
	... 35 more
Caused by: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
	at com.arangodb.internal.velocystream.internal.MessageStore.get(MessageStore.java:73)
	at com.arangodb.internal.velocystream.internal.ConnectionSync$1.call(ConnectionSync.java:87)
	at com.arangodb.internal.velocystream.internal.ConnectionSync$1.call(ConnectionSync.java:84)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.arangodb.internal.velocystream.internal.MessageStore.clear(MessageStore.java:96)
	at com.arangodb.internal.velocystream.internal.VstConnection$1.call(VstConnection.java:171)
	at com.arangodb.internal.velocystream.internal.VstConnection$1.call(VstConnection.java:151)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Reached the end of the stream.
	at com.arangodb.internal.velocystream.internal.VstConnection.readBytesIntoBuffer(VstConnection.java:289)
	at com.arangodb.internal.velocystream.internal.VstConnection.readBytes(VstConnection.java:281)
	at com.arangodb.internal.velocystream.internal.VstConnection.readChunk(VstConnection.java:258)
	at com.arangodb.internal.velocystream.internal.VstConnection$1.call(VstConnection.java:162)
	... 5 more
````

**Repeated Test Runs Causes Server Crash**
Running the failing test several times eventually causes my ArangoDB server instance to crash.
Here are the server logs:-
````
Attaching to arangodb_arangodb_1
arangodb_1  | choosing Rocksdb storage engine
arangodb_1  | 2018-04-17T09:46:44Z [1] INFO ArangoDB 3.3.7 [linux] 64bit, using jemalloc, build tags/v3.3.7-0-gbde36eb131, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.1.0f  25 May 2017
arangodb_1  | 2018-04-17T09:46:44Z [1] INFO {authentication} Jwt secret not specified, generating...
arangodb_1  | 2018-04-17T09:46:44Z [1] INFO detected operating system: Linux version 4.9.87-linuxkit-aufs (root@95fa5ec30613) (gcc version 6.4.0 (Alpine 6.4.0) ) #1 SMP Wed Mar 14 15:12:16 UTC 2018
arangodb_1  | 2018-04-17T09:46:44Z [1] INFO using storage engine rocksdb
arangodb_1  | 2018-04-17T09:46:44Z [1] INFO {cluster} Starting up with role SINGLE
arangodb_1  | 2018-04-17T09:46:44Z [1] INFO {syscall} file-descriptors (nofiles) hard limit is 1048576, soft limit is 1048576
arangodb_1  | 2018-04-17T09:46:44Z [1] INFO {authentication} Authentication is turned on (system only), authentication for unix sockets is turned on
arangodb_1  | 2018-04-17T09:46:44Z [1] WARNING {memory} /proc/sys/vm/overcommit_memory is set to '1'. It is recommended to set it to a value of 2
arangodb_1  | 2018-04-17T09:46:44Z [1] WARNING {memory} execute 'sudo bash -c "echo 2 > /proc/sys/vm/overcommit_memory"'
arangodb_1  | 2018-04-17T09:46:45Z [1] INFO using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
arangodb_1  | 2018-04-17T09:46:46Z [1] INFO ArangoDB (version 3.3.7 [linux]) is ready for business. Have fun!
Exception in thread Thread-3:
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 386, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 382, in _make_request
  File "http/client.py", line 1331, in getresponse
  File "http/client.py", line 297, in begin
  File "http/client.py", line 266, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 440, in send
  File "site-packages/urllib3/connectionpool.py", line 649, in urlopen
  File "site-packages/urllib3/util/retry.py", line 357, in increment
  File "site-packages/urllib3/packages/six.py", line 685, in reraise
  File "site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 386, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 382, in _make_request
  File "http/client.py", line 1331, in getresponse
  File "http/client.py", line 297, in begin
  File "http/client.py", line 266, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "compose/cli/log_printer.py", line 166, in tail_container_logs
  File "compose/cli/log_printer.py", line 197, in wait_on_exit
  File "compose/container.py", line 258, in wait
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1237, in wait
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 190, in _post
  File "site-packages/requests/sessions.py", line 555, in post
  File "site-packages/requests/sessions.py", line 508, in request
  File "site-packages/requests/sessions.py", line 618, in send
  File "site-packages/requests/adapters.py", line 490, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))`
````

At this point, my entire Docker daemon crashes.

**Comment by mpv1989** [comment]
I was not able to reproduce your problem.

When I take a look into the posted logs I see python logs. Since we don't have any python code in our DB could something different cause problems with your docker container or daemon?

**Comment by gbjbaaha** [comment]
Thanks for the feedback.
I'm starting to suspect this is something to do with Docker rather than ArangoDB. Interestingly similar behavior with regards to the Docker daemon crashing can be seen in this report:-
[https://github.com/joowani/python-arango/issues/29]

I will move my tests over to running Arango under Linux native and post back my results here which may take me a few days due to other commitments. 

If it helps anyone else experimenting with Arango under Docker, I ran my Docker daemon with debug tracing and reproduced the failure. It looks like something is failing down in the Docker networking layer which is then aborting the entire Docker VM.
Here are the logs for info:-
```
default	16:20:34.290852 +0100	com.docker.vpnkit	Socket.Stream: caught Socket is not connected
default	16:20:43.509546 +0100	com.docker.driver.amd64-linux	TX: Unable to accept incoming connection: fd 1024 > FD_SETSIZE 1024
default	16:20:43.529035 +0100	com.docker.vpnkit	Socket.Stream: caught Socket is not connected
default	16:20:53.299001 +0100	com.docker.driver.amd64-linux	TX: Unable to accept incoming connection: fd 1024 > FD_SETSIZE 1024
default	16:20:53.315803 +0100	com.docker.vpnkit	Socket.Stream: caught Socket is not connected
default	16:20:53.762690 +0100	com.docker.driver.amd64-linux	Assertion failed: (!REPLY_RING_EMPTY(sc)), function send_response_common, file src/lib/pci_virtio_sock.c, line 934.
default	16:20:53.762756 +0100	com.docker.driver.amd64-linux	virtio-net-vpnkit: initialising, opts="path=/Users/andrewhastie/Library/Containers/com.docker.docker/Data/s50,uuid=607c4aad-15d8-4cda-90a0-0715ffa0543e"
default	16:20:53.762800 +0100	com.docker.driver.amd64-linux	virtio-net-vpnkit: interface will have uuid 607c4aad-15d8-4cda-90a0-0715ffa0543e
default	16:20:53.762877 +0100	com.docker.driver.amd64-linux	virtio-net-vpnkit: Connection established with MAC=02:50:00:00:00:01 and MTU 1500
default	16:20:53.762916 +0100	com.docker.driver.amd64-linux	virtio-9p: initialising path=/Users/andrewhastie/Library/Containers/com.docker.docker/Data/s51,tag=port
default	16:20:53.762972 +0100	com.docker.driver.amd64-linux	linkname /Users/andrewhastie/Library/Containers/com.docker.docker/Data/vms/0/tty
default	16:20:53.763007 +0100	com.docker.driver.amd64-linux	COM1 connected to /dev/ttys005
default	16:20:53.763040 +0100	com.docker.driver.amd64-linux	COM1 linked to /Users/andrewhastie/Library/Containers/com.docker.docker/Data/vms/0/tty
default	16:20:53.771238 +0100	com.docker.driver.amd64-linux	Error watch events stream: unexpected EOF
default	16:20:53.778041 +0100	com.docker.driver.amd64-linux	error copying response body from Docker:  unexpected EOF
default	16:20:53.778115 +0100	com.docker.driver.amd64-linux	error closing response body from Docker:  unexpected EOF
default	16:20:53.778151 +0100	com.docker.driver.amd64-linux	proxy << GET /v1.30/events?filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Darangodb%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D
default	16:20:53.778361 +0100	com.docker.driver.amd64-linux	Error resync osxfs, waiting 2s before retry: error during connect: Get http://%2FUsers%2Fandrewhastie%2FLibrary%2FContainers%2Fcom.docker.docker%2FData%2Fvms%2F0%2F00000003.00000948/v1.37/containers/json?limit=0: EOF
default	16:20:53.779834 +0100	com.docker.osxfs	Unexpected exception: Socket.Closed
default	16:20:53.780691 +0100	com.docker.osxfs	Unexpected exception: Socket.Closed
default	16:20:53.783339 +0100	com.docker.driver.amd64-linux	proxy >> POST /v1.30/containers/7a6a4af6d4a1ccc20f5e6c816ce7d0f2eb6605ce80db6b3f569c1a78937a4b75/wait
default	16:20:53.783413 +0100	com.docker.driver.amd64-linux	Dial Socket /Users/andrewhastie/Library/Containers/com.docker.docker/Data/vms/0/00000003.00000948
default	16:20:53.783565 +0100	com.docker.driver.amd64-linux	dial unix /Users/andrewhastie/Library/Containers/com.docker.docker/Data/vms/0/00000003.00000948: connect: connection refused
default	16:20:53.798000 +0100	com.docker.vpnkit	Socket.Stream: caught Socket is not connected
default	16:20:53.798046 +0100	com.docker.vpnkit	Socket.Stream: caught Socket is not connected
default	16:20:53.879588 +0100	com.docker.vpnkit	Vmnet.Server.listen: read EOF so closing connection
default	16:20:53.879644 +0100	com.docker.vpnkit	Vmnet.Server.listen returning Ok()
default	16:20:53.879847 +0100	com.docker.driver.amd64-linux	Hypervisor subprocess has shutdown
default	16:20:53.884014 +0100	com.docker.supervisor	cannot read stdout from com.docker.driver.amd64-linux: EOF
default	16:20:53.884320 +0100	com.docker.supervisor	Reap com.docker.driver.amd64-linux (pid: 5329): <nil>
default	16:20:53.884406 +0100	com.docker.supervisor	cannot read stderr from com.docker.driver.amd64-linux: EOF
default	16:20:53.884473 +0100	com.docker.supervisor	Stop 1 children with order 1: [com.docker.driver.amd64-linux (pid: 5329)]
default	16:20:53.884515 +0100	com.docker.supervisor	Supervisor caught an error
default	16:20:53.884574 +0100	com.docker.supervisor	StopAll
default	16:20:53.884609 +0100	com.docker.supervisor	Stop 2 children with order 2: [com.docker.osxfs (pid: 5327) com.docker.vpnkit (pid: 5328)]
default	16:20:53.884669 +0100	com.docker.supervisor	Send signal terminated to com.docker.osxfs (pid: 5327)
default	16:20:53.884790 +0100	com.docker.supervisor	Send signal terminated to com.docker.vpnkit (pid: 5328)
default	16:20:53.887307 +0100	com.docker.supervisor	cannot read stderr from com.docker.osxfs: EOF
default	16:20:53.887380 +0100	com.docker.supervisor	cannot read stdout from com.docker.osxfs: EOF
default	16:20:53.887408 +0100	com.docker.supervisor	Reap com.docker.osxfs (pid: 5327): signal: terminated
default	16:20:53.904782 +0100	com.docker.supervisor	cannot read stderr from com.docker.vpnkit: EOF
default	16:20:53.904835 +0100	com.docker.supervisor	cannot read stdout from com.docker.vpnkit: EOF
default	16:20:53.904862 +0100	com.docker.supervisor	Reap com.docker.vpnkit (pid: 5328): signal: terminated
default	16:20:53.986116 +0100	com.docker.supervisor	Supervisor has failed, shutting down

```












https://github.com/joowani/python-arango/issues/29

**Comment by gbjbaaha** [comment]
Repeated my tests using the following and I can still reproduce the problem at will:-

Ubuntu 16.04 running on Amazon EC2 (t2Small with 2GB)
Arango  arangodb3-3.3.7-1_amd64.deb
Linux Kernel configured as per documentation

As before, the test client run fails after about 1,900 loops with the "Reached end of stream" Exception. At this point, the arangod.log.supervisor shows a child process terminating and the supervisor starts a new child process.

After repeating these tests about 5 times, the HTTP connection into the server appears to hang (you cannot access the web console) with the following logs:-

Client Logs:-
```
com.arangodb.ArangoDBException: Response: 500, Error: 3 - out of memory (while executing) (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/RestHandler/RestCursorHandler.cpp:135)

	at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:53)
	at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:116)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:143)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:48)
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:100)
	at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:47)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:53)
	at com.arangodb.ArangoDatabase.query(ArangoDatabase.java:359)
	at com.synalogik.specification.microservice.TestArangoDB.testReadGlobalConfig(TestArangoDB.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

/var/log/arangod.log
```
2018-04-19T08:36:33Z [5129] WARNING {memory} execute 'sudo bash -c "echo 100 > /proc/sys/vm/overcommit_ratio"'
2018-04-19T08:36:34Z [5129] INFO using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
2018-04-19T08:36:34Z [5129] INFO ArangoDB (version 3.3.7 [linux]) is ready for business. Have fun!
2018-04-19T08:38:11Z [5129] ERROR {threads} scheduler loop caught exception: std::bad_alloc
```

/var/log/arangod.log.supervisor
```
2018-04-19T08:34:46Z [4841] ERROR {startup} child process 4842 terminated unexpectedly, exit status 2. will now start a new child process
2018-04-19T08:34:46Z [4841] INFO {startup} supervisor has forked a child process with pid 4998
2018-04-19T08:36:33Z [4841] INFO {startup} waitpid woke up with return value 4998 and status 512 and DONE = false
2018-04-19T08:36:33Z [4841] ERROR {startup} child process 4998 terminated unexpectedly, exit status 2. will now start a new child process
2018-04-19T08:36:33Z [4841] INFO {startup} supervisor has forked a child process with pid 5129
```

*Conclusion*
A classic case of not releasing resources in my client code. What the driver documentation fails to mention is that if you do not explicitly release the connections into the server, you will eventually exhaust resources. So, all I needed to do was to add a call to shutdown the ArangoDB instance as in the following code fragment:-
```
for(int i=0; i<10000; i++)
        {
            ArangoDatabase dbCon = new ArangoDB.Builder().host(host, 8529).user("root").password("????").maxConnections(1).useProtocol(Protocol.VST).build().db("sgis");
            List<String> results = new ArrayList<>();
            String aql = "FOR s in customer_configs" +
                    "     FILTER s.document_type == @DOCTYPE" +
                    "     RETURN s.sgis_url";
            Map<String, Object> params = new MapBuilder().put("DOCTYPE", "GLOBAL_CONFIGURATION").get();
            ArangoCursor<String> cursor = dbCon.query(aql, params, null, String.class);

            while (cursor.hasNext())
            {
                System.out.println(cursor.next());
            }

            cursor.close();
            dbCon.arango().shutdown();    // <<<<<<<<<<<<<<<<<<<< 
        }
```

Can I suggest that the documentation (both the Reference Documentation and the JavaDocs) makes this requirement more clear? Whilst it is not such an issue for standard Java applications, if you're using JEE features such as Servlets, JAX-RS or stateless EJBs or any multi-threaded environment, you need to consider how you are going to handle the ArangoDB and ArangoDatabase objects as it's far too easy to get this wrong without realising it and crash your database server instance.

**Comment by mpv1989** [comment]
I added the requested docs. Thanks for your feedback
