### ISSUE TITLE
java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.

### ISSUE THREAD

**Issue by rachitjoshi9** [arangodb/arangodb-java-driver#217]
I am using it in java spring boot --
=====================================
This is how my POM looks --

<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<dependency>
			<groupId>com.arangodb</groupId>
			<artifactId>arangodb-spring-data</artifactId>
			<version>2.0.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.3</version>
		</dependency>
	</dependencies>

Configuration method ---------
============================================
	@Override
	public Builder arango() {
		return new ArangoDB.Builder().host(host, port).user(user).password(password).useSsl(false).maxConnections(10);
	}
================================================
Repository class--
============================
public interface NotificationRepository<T> extends ArangoRepository<T> {
	
}
=================================
Error comes on calling save method.
========================================
notificationRepository.save(notification)

it works fine for localhost, when i am passing it my development server (Running with ssl)  credentials it gives error.

First it was giving authentication error when all my credentials were for server correct, then it started giving another error.

2018-07-30 20:33:07.480  INFO 5696 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2018-07-30 20:33:07.480  INFO 5696 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2018-07-30 20:33:07.495  INFO 5696 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 14 ms
2018-07-30 20:33:08.264 ERROR 5696 --- [pool-1-thread-1] c.a.i.v.internal.MessageStore            : Reached the end of the stream.

java.io.IOException: Reached the end of the stream.
	at com.arangodb.internal.velocystream.internal.VstConnection.readBytesIntoBuffer(VstConnection.java:286) ~[arangodb-java-driver-4.3.2.jar:na]
	at com.arangodb.internal.velocystream.internal.VstConnection.readBytes(VstConnection.java:278) ~[arangodb-java-driver-4.3.2.jar:na]
	at com.arangodb.internal.velocystream.internal.VstConnection.readChunk(VstConnection.java:255) ~[arangodb-java-driver-4.3.2.jar:na]
	at com.arangodb.internal.velocystream.internal.VstConnection$1.call(VstConnection.java:159) [arangodb-java-driver-4.3.2.jar:na]
	at com.arangodb.internal.velocystream.internal.VstConnection$1.call(VstConnection.java:148) [arangodb-java-driver-4.3.2.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_121]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_121]

2018-07-30 20:33:08.286 ERROR 5696 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.arangodb.ArangoDBException: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.] with root cause

java.io.IOException: Reached the end of the stream.
	at com.arangodb.internal.velocystream.internal.VstConnection.readBytesIntoBuffer(VstConnection.java:286) ~[arangodb-java-driver-4.3.2.jar:na]
	at com.arangodb.internal.velocystream.internal.VstConnection.readBytes(VstConnection.java:278) ~[arangodb-java-driver-4.3.2.jar:na]
	at com.arangodb.internal.velocystream.internal.VstConnection.readChunk(VstConnection.java:255) ~[arangodb-java-driver-4.3.2.jar:na]
	at com.arangodb.internal.velocystream.internal.VstConnection$1.call(VstConnection.java:159) ~[arangodb-java-driver-4.3.2.jar:na]
	at com.arangodb.internal.velocystream.internal.VstConnection$1.call(VstConnection.java:148) ~[arangodb-java-driver-4.3.2.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_121]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_121]

**Comment by mpv1989** [comment]
Hi @rachitjoshi9,

normally this error only occurs when the ArangoDB server is not reachable anymore. The reason could be that the connection is closed on server side. You should take a look into your ArangoDB server logs.

If you run a cluster you want the logs of the coordinator you're connecting to.

**Comment by mpv1989** [comment]
I am closing this. Feel free to open it again if your problem still exists
