### ISSUE TITLE
importDocuments throws `VPackValueTypeException: Expecting type ARRAY` in silent mode

### ISSUE THREAD

**Issue by grzegorz-aniol** [arangodb/arangodb-java-driver#241]
### arangodb version: 3.4.0-rc.5

There is an exception while batch insert of documents when silent mode is used:

```java

List<BaseDocument> docs = ...
...
DocumentCreateOptions docCreateOpts = new DocumentCreateOptions()
        .silent(true)
        .overwrite(overwrite)
        .returnNew(false)
        .returnOld(false);

db.collection("collection").importDocuments(docs, docCreateOpts);
```

```
com.arangodb.ArangoDBException: com.arangodb.velocypack.exception.VPackValueTypeException: Expecting type ARRAY
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:74)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:63)
	at com.arangodb.internal.ArangoCollectionImpl.insertDocuments(ArangoCollectionImpl.java:97)
```

The possible solution is to omit proceeding multidocument response body in method:
`com.arangodb.internal.InternalArangoCollection#insertDocumentsResponseDeserializer` : 

```java
  ...
  final VPackSlice body = response.getBody();
  if (body.isArray()) {
    for (final Iterator<VPackSlice> iterator = body.arrayIterator(); iterator.hasNext();) {
    ..
    }
  }
  ...
```

**Comment by jaredpetersen** [comment]
When will this be released? I'm running into this bug right now as well.

**Comment by hkernbach** [comment]
@jaredpetersen new build pushed to maven central repository about 4 hours ago. Not yet live, but should be soon.
