### ISSUE TITLE
could not start all traversal engines timeout in cluster operation

### ISSUE THREAD

**Issue by date-dute** [arangodb/arangodb-java-driver#251]
## My Environment

* __ArangoDB Version__: 3.3.7
* __Storage Engine__: RocksDB
* __Deployment Mode__: Cluster
* __Deployment Strategy__:   
* __Configuration__: 32-bit 64G
* __Infrastructure__:               
* __Operating System__: Centos 7.5
* __Total RAM in your machine__: 128G
* __Disks in use__: 500G       
* __Used Package__:              

## Component, Query & Data

__Affected feature__:
arango-java-driver 4.2.2

__AQL query (if applicable)__:
query graph

__AQL explain (if applicable)__:

__Dataset__:

7000w+

__Size of your Dataset on disk__:

7000w+

__Replication Factor & Number of Shards (Cluster only)__:

3

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
Connect timeOut

__Expected result__:

How to solve this problem？

**Comment by dothebart** [comment]
this may occur if your system is overloaded. Aside of that, without any information about your system or your setup, I can't hint you any further. Since this happenes inside of the ArangoDB cluster, please open a github issue on the arangodb repsoitory, if this didn't already help. 
I will close this issue now.

**Comment by date-dute** [comment]
[2019-03-14 12:14:26]-[ERROR]-[com.arangodb.internal.velocystream.internal.MessageStore:89]-连接超时 (Read failed)
java.net.SocketException: 连接超时 (Read failed)
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_162]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_162]
        at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_162]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_162]
        at com.arangodb.internal.velocystream.internal.Connection.readBytesIntoBuffer(Connection.java:266) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.Connection.readBytes(Connection.java:260) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.Connection.readChunk(Connection.java:237) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.Connection$1.call(Connection.java:148) [arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.Connection$1.call(Connection.java:137) [arangodb-java-driver-4.2.2.jar!/:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
[2019-03-14 12:14:26]-[ERROR]-[com.haizhi.graph.server.arango.search.ArangoSearchDAOImpl:121]-traverse error:
com.arangodb.ArangoDBException: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.net.SocketException: 连接超时 (Read failed)
        at com.arangodb.internal.velocystream.internal.ConnectionSync.write(ConnectionSync.java:92) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.VstCommunicationSync.send(VstCommunicationSync.java:147) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:131) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:46) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:96) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:46) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:58) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:47) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.ArangoDatabase.query(ArangoDatabase.java:300) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.haizhi.graph.server.arango.search.ArangoSearchDAOImpl.rawSearch(ArangoSearchDAOImpl.java:101) ~[graph-server-arango-2.0.1-SNAPSHOT.jar!/:2.0.1-SNAPSHOT]
        at com.haizhi.graph.server.arango.search.ArangoSearchDAOImpl.lambda$null$1(ArangoSearchDAOImpl.java:231) ~[graph-server-arango-2.0.1-SNAPSHOT.jar!/:2.0.1-SNAPSHOT]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.net.SocketException: 连接超时 (Read failed)
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_162]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_162]
        at com.arangodb.internal.velocystream.internal.ConnectionSync.write(ConnectionSync.java:88) ~[arangodb-java-driver-4.2.2.jar!/:?]
        ... 14 more
Caused by: com.arangodb.ArangoDBException: java.net.SocketException: 连接超时 (Read failed)
        ... 14 more
Caused by: com.arangodb.ArangoDBException: java.net.SocketException: 连接超时 (Read failed)
        at com.arangodb.internal.velocystream.internal.MessageStore.get(MessageStore.java:73) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.ConnectionSync$1.call(ConnectionSync.java:82) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.ConnectionSync$1.call(ConnectionSync.java:79) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_162]
        at com.arangodb.internal.velocystream.internal.MessageStore.clear(MessageStore.java:96) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.Connection$1.call(Connection.java:157) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.Connection$1.call(Connection.java:137) ~[arangodb-java-driver-4.2.2.jar!/:?]
        ... 4 more
Caused by: java.net.SocketException: 连接超时 (Read failed)
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_162]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_162]
        at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_162]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_162]
        at com.arangodb.internal.velocystream.internal.Connection.readBytesIntoBuffer(Connection.java:266) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.Connection.readBytes(Connection.java:260) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.Connection.readChunk(Connection.java:237) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.Connection$1.call(Connection.java:148) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.Connection$1.call(Connection.java:137) ~[arangodb-java-driver-4.2.2.jar!/:?]
        ... 4 more
[2019-03-14 12:14:26]-[ERROR]-[com.haizhi.graph.server.arango.search.ArangoSearchDAOImpl:121]-traverse error:
com.arangodb.ArangoDBException: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.net.SocketException: 连接超时 (Read failed)
        at com.arangodb.internal.velocystream.internal.ConnectionSync.write(ConnectionSync.java:92) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.VstCommunicationSync.send(VstCommunicationSync.java:147) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:131) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:46) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:96) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:46) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:58) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:47) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.ArangoDatabase.query(ArangoDatabase.java:300) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.haizhi.graph.server.arango.search.ArangoSearchDAOImpl.rawSearch(ArangoSearchDAOImpl.java:101) ~[graph-server-arango-2.0.1-SNAPSHOT.jar!/:2.0.1-SNAPSHOT]
        at com.haizhi.graph.server.arango.search.ArangoSearchDAOImpl.lambda$null$1(ArangoSearchDAOImpl.java:231) ~[graph-server-arango-2.0.1-SNAPSHOT.jar!/:2.0.1-SNAPSHOT]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.net.SocketException: 连接超时 (Read failed)
Caused by: com.arangodb.ArangoDBException: java.net.SocketException: 连接超时 (Read failed)
        at com.arangodb.internal.velocystream.internal.MessageStore.get(MessageStore.java:73) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.ConnectionSync$1.call(ConnectionSync.java:82) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.ConnectionSync$1.call(ConnectionSync.java:79) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_162]
        at com.arangodb.internal.velocystream.internal.MessageStore.clear(MessageStore.java:96) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.Connection$1.call(Connection.java:157) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.Connection$1.call(Connection.java:137) ~[arangodb-java-driver-4.2.2.jar!/:?]
        ... 4 more
Caused by: java.net.SocketException: 连接超时 (Read failed)
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_162]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_162]
        at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_162]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_162]
        at com.arangodb.internal.velocystream.internal.Connection.readBytesIntoBuffer(Connection.java:266) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.Connection.readBytes(Connection.java:260) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.Connection.readChunk(Connection.java:237) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.Connection$1.call(Connection.java:148) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.internal.Connection$1.call(Connection.java:137) ~[arangodb-java-driver-4.2.2.jar!/:?]
        ... 4 more
[2019-03-14 12:14:26]-[ERROR]-[com.haizhi.graph.server.arango.search.ArangoSearchDAOImpl:121]-traverse error:
com.arangodb.ArangoDBException: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.net.SocketException: 连接超时 (Read failed)
        at com.arangodb.internal.velocystream.internal.ConnectionSync.write(ConnectionSync.java:92) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.VstCommunicationSync.send(VstCommunicationSync.java:147) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:131) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:46) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:96) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:46) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:58) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:47) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.arangodb.ArangoDatabase.query(ArangoDatabase.java:300) ~[arangodb-java-driver-4.2.2.jar!/:?]
        at com.haizhi.graph.server.arango.search.ArangoSearchDAOImpl.rawSearch(ArangoSearchDAOImpl.java:101) ~[graph-server-arango-2.0.1-SNAPSHOT.jar!/:2.0.1-SNAPSHOT]
        at com.haizhi.graph.server.arango.search.ArangoSearchDAOImpl.lambda$null$1(ArangoSearchDAOImpl.java:231) ~[graph-server-arango-2.0.1-SNAPSHOT.jar!/:2.0.1-SNAPSHOT]

**Comment by date-dute** [comment]
exception message，connect time out

**Comment by dothebart** [comment]
Do you see coordinator PIDs change in the logfiles?

**Comment by date-dute** [comment]
How do I go about it？

**Comment by date-dute** [comment]
There is no pid in the logfile . by the process？？

**Comment by dothebart** [comment]
edited your original post. please edit & fill out.

**Comment by date-dute** [comment]
ArangoDB版本:3.3.7

存储引擎:raskdb

部署模式:集群

部署策略:

配置: 32位 64G

基础设施:

操作系统: centos 7.5

机器的总RAM: 128G

磁盘在使用: 500G

使用包: arango-java-driver 4.2.2

组件、查询和数据

受影响的特点:连接超时，读取超时


AQL查询(如适用):图查询


AQL解释(如适用):


数据集: 7000w+


磁盘上数据集的大小:7000w+


复制因子和碎片数量(仅集群): 3


步骤来复制

问题:连接超时

**Comment by dothebart** [comment]
I may repeat myself, but please edit your original post, and english please.

**Comment by date-dute** [comment]
ArangoDB Version:3.3.7
Storage Engine:raskdb
Deployment Mode:cluster
Deployment Strategy:
Configuration:32Bit 64G
Infrastructure:
Operating System:centos 7.5
Total RAM in your machine:128G
Disks in use:500G
Used Package:arango-java-driver 4.2.2
Component, Query & Data
Affected feature:Connect timeOut

AQL query (if applicable):query graph

AQL explain (if applicable):

Dataset:7000w+

Size of your Dataset on disk:7000w+

Replication Factor & Number of Shards (Cluster only):3

**Comment by Simran-B** [comment]
Edited the original post. Still incomplete:

**Deployment Strategy** - Did you start the cluster manually (`arangod` binary) or using the ArangoDB Starter (`arangodb` binary)?
**Configuration:** 32-bit 64G - What is this supposed to mean? Is it a 32-bit system? What does 64G mean if you say further down that the machine has 128G RAM?
**Infrastructure** - own hardware or some cloud provider?
**Used Package** - probably .rpm if you use CentOS...
**AQL query** - you need to be more precise then "query graph"
**Dataset:** 7000w+ - What does the `w` stand for? Also, we need a better description of the dataset, like what collections you have with what indexes, how the documents are structured, how many documents are in each involved collection etc.
**Replication Factor & Number of Shards** - so RF 3 and 3 shards?

**Comment by dothebart** [comment]
in general patch release 3.3.22 is available which obviously contains lots of bugfixes. Please upgrade to the latest version and check back whether the error persists. 
See https://docs.arangodb.com/3.4/Manual/Upgrading/ for details about upgrading.

**Comment by rashtao** [comment]
Closing due to inactivity, please reopen if still relevant.
