### ISSUE TITLE
Not specifying aquireHostList crashes the driver

### ISSUE THREAD

**Issue by Queatz** [arangodb/arangodb-java-driver#269]
This crashes:
```
new ArangoDB.Builder()
                    .user(DB_USER)
                    .password(DB_PASS)
                    .registerModule(new VPackJdk8Module())
                    .build()
                    .db(DB_DATABASE);
```
With:
```
java.lang.NullPointerException
	at com.arangodb.internal.InternalArangoDBBuilder.createHostResolver(InternalArangoDBBuilder.java:206)
	at com.arangodb.ArangoDB$Builder.build(ArangoDB.java:617)
```

Crisis avoided by adding `.acquireHostList(false)`:
```
new ArangoDB.Builder()
                    .user(DB_USER)
                    .password(DB_PASS)
                    .acquireHostList(false)
                    .registerModule(new VPackJdk8Module())
                    .build()
                    .db(DB_DATABASE);
```

**Comment by hkernbach** [comment]
Thanks for opening up the issue. This problem is solved in the latest release of the ArangoDB Java Driver 5.0.7
