### ISSUE TITLE
driver error..  c.a.i.v.i.MessageStore: Reached the end of the stream

### ISSUE THREAD

**Issue by D0LLAR** [arangodb/arangodb-java-driver#272]
Arrango is on version 3.4.6-1 across all environments.

Java java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

Jmeter is 5.1.1

Im seeing an error on fire up ..

2019-07-03 12:24:37,386 ERROR c.a.i.v.i.MessageStore: Reached the end of the stream.
java.io.IOException: Reached the end of the stream.
	at com.arangodb.internal.velocystream.internal.VstConnection.readBytesIntoBuffer(VstConnection.java:262) ~[arangodb-java-driver-5.0.5-SNAPSHOT-standalone.jar:?]
	at com.arangodb.internal.velocystream.internal.VstConnection.readBytes(VstConnection.java:254) ~[arangodb-java-driver-5.0.5-SNAPSHOT-standalone.jar:?]
	at com.arangodb.internal.velocystream.internal.VstConnection.readChunk(VstConnection.java:231) ~[arangodb-java-driver-5.0.5-SNAPSHOT-standalone.jar:?]
	at com.arangodb.internal.velocystream.internal.VstConnection$1.call(VstConnection.java:141) [arangodb-java-driver-5.0.5-SNAPSHOT-standalone.jar:?]
	at com.arangodb.internal.velocystream.internal.VstConnection$1.call(VstConnection.java:124) [arangodb-java-driver-5.0.5-SNAPSHOT-standalone.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151

**Comment by sleto-it** [comment]
Hi Tim - Please use Jira. Thanks,
