### ISSUE TITLE
Test ArangoDatabaseTest.getCollectionsExcludeSystem() fails when packaging master branch

### ISSUE THREAD

**Issue by rkhaja** [arangodb/arangodb-java-driver#274]
When packaging the **master** branch of the arangodb-java-driver, the **ArangoDatabaseTest.getCollectionsExcludeSystem()** fails.

Here are details of the failure:
```
getCollectionsExcludeSystem[0](com.arangodb.ArangoDatabaseTest)  Time elapsed: 0.023 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <0>
     but: was <2>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.arangodb.ArangoDatabaseTest.getCollectionsExcludeSystem(ArangoDatabaseTest.java:514)
...
```

**Comment by rkhaja** [comment]
It appears that the source of this problem is a previously run test.

Here is the source for **ArangoGraphTest.drop()**:
```
	@Test
	public void drop() {
		final String edgeCollection  = "edge_drop";
		final String vertexCollection = "vertex_drop";
		final String graph = GRAPH_NAME + "_drop";
		final GraphEntity result = db.graph(graph).create(Collections
				.singleton(new EdgeDefinition().collection(edgeCollection).from(vertexCollection).to(vertexCollection)));
		assertThat(result, is(notNullValue()));
		db.graph(graph).drop();
		assertThat(db.collection(edgeCollection).exists(), is(true));
		assertThat(db.collection(vertexCollection).exists(), is(true));
	}
```
This test creates a graph with 2 collections: **edge_drop** and **vertex_drop**, then drops the graph and checks that the collections that were created still exist.

**Comment by rkhaja** [comment]
Closing issue, since #274 was merged.

**Comment by rkhaja** [comment]
Thank you!
