### ISSUE TITLE
"Reached the end of the stream" exception

### ISSUE THREAD

**Issue by nickcodefresh** [arangodb/arangodb-java-driver#332]
Hi. 

I'm using the ArangoDB driver v6.3.0 and ArangoDB v3.4.7 and creating a simple cursor using the following code:
```
final String query = "FOR t IN mycollection FILTER t.annotationId == null RETURN t";
  try (ArangoCursor<BaseDocument> cursor = arangoDb.query(query, null, null, BaseDocument.class)) {
     cursor.forEach(d -> {
        docs.put((Long) d.getProperties().get("objectId"), d);
     });
}
```
I get the following exception:
```
Caused by: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.arangodb.internal.velocystream.internal.VstConnectionSync.write(VstConnectionSync.java:91)
	... 11 common frames omitted
Caused by: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
	at com.arangodb.internal.velocystream.internal.MessageStore.get(MessageStore.java:72)
	at com.arangodb.internal.velocystream.internal.VstConnectionSync.lambda$write$0(VstConnectionSync.java:87)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.arangodb.internal.velocystream.internal.MessageStore.clear(MessageStore.java:95)
	at com.arangodb.internal.velocystream.internal.VstConnection.lambda$open$0(VstConnection.java:155)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
any ideas why this is happening? I'm truly baffled by it

**Comment by rashtao** [comment]
Unfortunately I cannot reproduce your issue. Can you provide additional details to help understanding better? (eg. jvm version, db deployment topology, driver configuration).
Or maybe can you reproduce with a working example? Eg. forking the driver git repository and writing a failing test?

**Comment by rashtao** [comment]
@nickcodefresh I am closing this due to inactivity. Feel free to reopen it in case you can reproduce the issue.
