### ISSUE TITLE
Unable to use Typed Search Analyzers with VelocyJack

### ISSUE THREAD

**Issue by jebbench** [arangodb/arangodb-java-driver#340]
I'm trying to update to the latest version of the driver and found that the `AnalyzerEntity` class has been deprecated; unfortunately when I convert my code to use the SearchAnalyzer class I get a exception from Jackson:
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.arangodb.entity.arangosearch.analyzer.SearchAnalyzer` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
com.arangodb.ArangoDBException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.arangodb.entity.arangosearch.analyzer.SearchAnalyzer` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
	at com.arangodb.VelocyJack.deserialize(VelocyJack.java:117)
	at com.arangodb.internal.ArangoExecutor.createResult(ArangoExecutor.java:42)
	at com.arangodb.internal.ArangoExecutorSync.lambda$execute$0(ArangoExecutorSync.java:57)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:72)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:57)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:53)
	at com.arangodb.internal.ArangoDatabaseImpl.createSearchAnalyzer(ArangoDatabaseImpl.java:434)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.arangodb.entity.arangosearch.analyzer.SearchAnalyzer` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1589)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1055)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:265)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3275)
	at com.arangodb.VelocyJack.deserialize(VelocyJack.java:112)
	... 87 more
```

Is there a workaround for this?

The code in question:
```
    try {
        db.getSearchAnalyzer("attribute")
    } catch (e: ArangoDBException){
        if(e.responseCode == 404){
            val analyzer = NormAnalyzer()
            analyzer.name = "attribute"
            analyzer.properties = NormAnalyzerProperties().apply {
                locale = "en"
                analyzerCase = SearchAnalyzerCase.lower
                isAccent = false
            }
            db.createSearchAnalyzer(analyzer)
        }
    }
```

**Comment by rashtao** [comment]
Thanks for reporting, fixed here: https://github.com/arangodb/arangodb-java-driver/commit/fd228ba374cbc35007c49f03aac62bf86a46f29c

**Comment by rashtao** [comment]
released in https://github.com/arangodb/arangodb-java-driver/releases/tag/v6.6.2

**Comment by jebbench** [comment]
Cheers - I can confirm that 6.6.2 fixes this for me.
