### ISSUE TITLE
java.net.SocketException: Socket closed 

### ISSUE THREAD

**Issue by agorobtsov** [arangodb/arangodb-java-driver#344]
Hi there!

My environment is:
ArangoDB: 3.5.2
arangodb-java-driver: 6.3.0

From time to time appeared strange floating issue (see stack trace below). This exception may be appeared in any request to db.

`
java.net.SocketException: Socket closed
--
  | at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118) ~[na:1.8.0_131]
  | at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[na:1.8.0_131]
  | at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_131]
  | at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.8.0_131]
  | at com.arangodb.internal.velocystream.internal.VstConnection.writeIntern(VstConnection.java:216) ~[arangodb-java-driver-6.3.0.jar!/:na]
  | at com.arangodb.internal.velocystream.internal.VstConnectionSync.write(VstConnectionSync.java:89) ~[arangodb-java-driver-6.3.0.jar!/:na]
  | at com.arangodb.internal.velocystream.VstCommunicationSync.send(VstCommunicationSync.java:140) ~[arangodb-java-driver-6.3.0.jar!/:na]
  | at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:126) ~[arangodb-java-driver-6.3.0.jar!/:na]
  | at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:42) ~[arangodb-java-driver-6.3.0.jar!/:na]
  | at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:125) ~[arangodb-java-driver-6.3.0.jar!/:na]
  | at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:47) ~[arangodb-java-driver-6.3.0.jar!/:na]
  | at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:72) ~[arangodb-java-driver-6.3.0.jar!/:na]
  | at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:62) ~[arangodb-java-driver-6.3.0.jar!/:na]
  | at com.arangodb.internal.ArangoGraphImpl.getVertexCollections(ArangoGraphImpl.java:85) ~[arangodb-java-driver-6.3.0.jar!/:na]

`

**Comment by rashtao** [comment]
This is an exception coming from the underlying networking layer, maybe because your network is unstable and the driver lost the connection with the server.

**Comment by agorobtsov** [comment]
I can't agree. With driver version 4.2.2 there are no errors.
Please also note if we specify  useProtocol(Protocol.HTTP_JSON) there are no error

**Comment by rashtao** [comment]
In VST connections, the socket is explicitly closed only when `VstConnection.close()` method is invoked (https://github.com/arangodb/arangodb-java-driver/blob/d00ddb1afe787199e604424020475953defd46b3/src/main/java/com/arangodb/internal/velocystream/internal/VstConnection.java#L177).
You may want to double check if you ever invoke it from your code.

Also the socket can be closed due to `ttl`, please check the related configuration documentation here:
https://www.arangodb.com/docs/3.6/drivers/java-reference-setup.html#connection-time-to-live

In case of the HTTP protocol, the communication is stateless and the client automatically opens a new connection in case the existing one is closed. So it is more tolerant in respect to temporary network connectivity problems.

**Comment by rashtao** [comment]
@agorobtsov 
Closing due to inactivity, please reopen if you have any update.
