### ISSUE TITLE
java.lang.IllegalStateException: Connection pool shut down

### ISSUE THREAD

**Issue by alexly25** [arangodb/arangodb-java-driver#352]
Hello

My environment is:
ArangoDB: 3.6.3
arangodb-java-driver: 4.6.1

We have changed default protocol(VST) to Protocol.HTTP_VPACK, because we have socketTimeout sometimes

Now, we have next issue sometimes:

> java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34) ~[httpcore-4.4.10.jar!/:4.4.10]
	at org.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:191) ~[httpcore-4.4.10.jar!/:4.4.10]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:267) ~[httpclient-4.5.6.jar!/:4.5.6]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176) ~[httpclient-4.5.6.jar!/:4.5.6]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.6.jar!/:4.5.6]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.6.jar!/:4.5.6]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.6.jar!/:4.5.6]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.6.jar!/:4.5.6]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.6.jar!/:4.5.6]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.6.jar!/:4.5.6]
	at com.arangodb.internal.http.HttpConnection.execute(HttpConnection.java:211) ~[arangodb-java-driver-4.6.1.jar!/:na]
	at com.arangodb.internal.http.HttpCommunication.execute(HttpCommunication.java:150) ~[arangodb-java-driver-4.6.1.jar!/:na]
	at com.arangodb.internal.http.HttpCommunication.execute(HttpCommunication.java:135) ~[arangodb-java-driver-4.6.1.jar!/:na]
	at com.arangodb.internal.http.HttpProtocol.execute(HttpProtocol.java:49) ~[arangodb-java-driver-4.6.1.jar!/:na]
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71) ~[arangodb-java-driver-4.6.1.jar!/:na]
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:53) ~[arangodb-java-driver-4.6.1.jar!/:na]
	at com.arangodb.internal.ArangoDatabaseImpl.query(ArangoDatabaseImpl.java:191) ~[arangodb-java-driver-4.6.1.jar!/:na]
	at com.arangodb.springframework.core.template.ArangoTemplate.query(ArangoTemplate.java:318) ~[arangodb-spring-data-2.3.0.jar!/:na]
	at com.database.opmanager.dao.repository.Repository.lambda$getAll$5(Repository.java:159) ~[classes!/:6.0.0]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287) ~[spring-retry-1.2.3.RELEASE.jar!/:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164) ~[spring-retry-1.2.3.RELEASE.jar!/:na]

Why can we get it?

// Perhaps we just should use more new arangodb-java-driver version

**Comment by rashtao** [comment]
I would recommend updating to the latest driver version.

Such exception should be thrown by the Apache Http client if the `PoolingHttpClientConnectionManager` has been already shut down. To understand why it happens you can debug invocations of `PoolingHttpClientConnectionManager#shutdown()` and `HttpConnection#close()`.

**Comment by rashtao** [comment]
@alexly25 
Closing due to inactivity, please reopen if you have any update.
