### ISSUE TITLE
Write thread blocking

### ISSUE THREAD

**Issue by Neverstop** [arangodb/arangodb-java-driver#354]
The following error occurred when I imported data to arangodb using atomic operations.

stack trace:
 java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000007359dbf80> (a java.util.concurrent.FutureTask)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
        at java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.arangodb.internal.velocystream.internal.VstConnectionSync.write(VstConnectionSync.java:90)
        at com.arangodb.internal.velocystream.VstCommunicationSync.send(VstCommunicationSync.java:138)
        at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:124)
        at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:40)
        at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:124)
        at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:46)
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:61)
        at com.arangodb.internal.ArangoCollectionImpl.insertDocuments(ArangoCollectionImpl.java:70)
        at com.huawei.poisson.knowledgegraph.repo.KnowledgeRepository.importGraphData(KnowledgeRepository.java:272)

What could be the cause of this？

**Comment by rashtao** [comment]
The thread is waiting here: https://github.com/arangodb/arangodb-java-driver/blob/d00ddb1afe787199e604424020475953defd46b3/src/main/java/com/arangodb/internal/velocystream/internal/VstConnectionSync.java#L90

What kind of exception do you get?
If you get `TimeoutException` then it is likely to be due to a request not being replied within the driver request timeout. 
Otherwise I guess you could get `InterruptedException` which is because your thread has been interrupted.

**Comment by rashtao** [comment]
Closing for now, please reopen if still relevant.
