### ISSUE TITLE
ArangoDatabase.route: path is double-encoded

### ISSUE THREAD

**Issue by wajda** [arangodb/arangodb-java-driver#357]
```java
db.route("foo:bar").get()
```
gives
```
java.util.concurrent.CompletionException: com.arangodb.ArangoDBException: Response: 404, Error: 404 - unknown path 'foo%253Abar'
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925)
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:913)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at com.arangodb.async.internal.velocystream.VstCommunicationAsync.lambda$execute$0(VstCommunicationAsync.java:66)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at com.arangodb.async.internal.velocystream.VstConnectionAsync.lambda$write$0(VstConnectionAsync.java:48)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at com.arangodb.internal.velocystream.internal.MessageStore.consume(MessageStore.java:62)
	at com.arangodb.internal.velocystream.internal.ChunkStore.checkCompleteness(ChunkStore.java:65)
	at com.arangodb.internal.velocystream.internal.ChunkStore.checkCompleteness(ChunkStore.java:59)
	at com.arangodb.internal.velocystream.internal.VstConnection.lambda$open$0(VstConnection.java:151)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.arangodb.ArangoDBException: Response: 404, Error: 404 - unknown path 'foo%253Abar'
	... 17 common frames omitted
```

Note the path in the error message - `foo%253Abar` instead of `foo%3Abar`.

A quick debugging led me to `ArangoExecutable.java:65`:

```java
protected Request request(final String database, final RequestType requestType, final String... path) {
        final Request request = new Request(database, requestType, createPath(path));   // <---- HERE !!!
        for (final Entry<String, String> header : context.getHeaderParam().entrySet()) {
            request.putHeaderParam(header.getKey(), header.getValue());
        }
        return request;
    }
```

In that method the `path` variable is already encoded, and calling `createPath(path)` results in double-encoding.

**Comment by rashtao** [comment]
Thanks for reporting, fixed in https://github.com/arangodb/arangodb-java-driver/commit/a3a95d7ff1a574f4a3eb0dc86b2e7553fe79c26f
