### ISSUE TITLE
Http Protocol Exception

### ISSUE THREAD

**Issue by aveiros** [arangodb/arangodb-java-driver#361]
While using this Java Drive with the HTTP_JSON protocol, I get the following exception. 

`java.lang.NoClassDefFoundError: org/apache/http/conn/HttpClientConnectionManager; Processor Administratively Yielded for 1 sec: java.lang.NoClassDefFoundError: org/apache/http/conn/HttpClientConnectionManager
java.lang.NoClassDefFoundError: org/apache/http/conn/HttpClientConnectionManager
        at com.arangodb.internal.http.HttpConnection$Builder.build(HttpConnection.java:150)
        at com.arangodb.internal.http.HttpConnectionFactory.create(HttpConnectionFactory.java:51)
        at com.arangodb.internal.net.ConnectionPoolImpl.createConnection(ConnectionPoolImpl.java:57)
        at com.arangodb.internal.net.ConnectionPoolImpl.connection(ConnectionPoolImpl.java:66)
        at com.arangodb.internal.net.HostImpl.connection(HostImpl.java:54)
        at com.arangodb.internal.http.HttpCommunication.execute(HttpCommunication.java:80)
        at com.arangodb.internal.http.HttpProtocol.execute(HttpProtocol.java:46)
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:57)
        at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:53)
        at com.arangodb.internal.ArangoCollectionImpl.importDocuments(ArangoCollectionImpl.java:92)`

Callers need to manually include the apache httpclient.

Using version: 6.7.4

Thanks.

**Comment by rashtao** [comment]
You should explicitly include Apache httpclient: 
https://www.arangodb.com/docs/stable/drivers/java-reference-setup.html#network-protocol

**Comment by aveiros** [comment]
Thanks @rashtao. Closing this.
