### ISSUE TITLE
"java.io.IOException: Reached the end of the stream" occasionally thrown

### ISSUE THREAD

**Issue by DerekHou** [arangodb/arangodb-java-driver#371]
Hi all,
Using ArangoDb 3.7.3 with java-driver 6.7.3 (through arangodb-spring-data 3.3.0), the IOException "Reached the end of the stream" is thrown up occasionally (very difficult to reproduce). The statck trace is as below:

Caused by: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.arangodb.internal.velocystream.internal.VstConnectionSync.write(VstConnectionSync.java:90)
	... 97 common frames omitted
Caused by: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
	at com.arangodb.internal.velocystream.internal.MessageStore.get(MessageStore.java:71)
	at com.arangodb.internal.velocystream.internal.VstConnectionSync.lambda$write$0(VstConnectionSync.java:86)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.arangodb.internal.velocystream.internal.MessageStore.clear(MessageStore.java:94)
	at com.arangodb.internal.velocystream.internal.VstConnection.lambda$open$0(VstConnection.java:155)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 common frames omitted
Caused by: java.io.IOException: Reached the end of the stream.
	at com.arangodb.internal.velocystream.internal.VstConnection.readBytesIntoBuffer(VstConnection.java:273)
	at com.arangodb.internal.velocystream.internal.VstConnection.readBytes(VstConnection.java:265)
	at com.arangodb.internal.velocystream.internal.VstConnection.readChunk(VstConnection.java:240)
	at com.arangodb.internal.velocystream.internal.VstConnection.lambda$open$0(VstConnection.java:146)
	... 4 common frames omitted

Is there any possible reason for this exception (FYI, the ArangoDb server runs in docker)? Thanks

**Comment by rashtao** [comment]
It means that the connection has been closed from the server side. Maybe because it remained idle too long. 
To understand why you can enable the finer log levels on the coordinators (`--log.level requests=trace --log.level communication=trace `).
Also consider using the latest driver version (https://github.com/arangodb/arangodb-java-driver/releases/tag/v6.8.0) which comes with a configurable VST keep-alive feature.

**Comment by DerekHou** [comment]
> It means that the connection has been closed from the server side. Maybe because it remained idle too long.
> To understand why you can enable the finer log levels on the coordinators (`--log.level requests=trace --log.level communication=trace `).
> Also consider using the latest driver version (https://github.com/arangodb/arangodb-java-driver/releases/tag/v6.8.0) which comes with a configurable VST keep-alive feature.

@rashtao Thanks, I will try to upgrade the driver

**Comment by rashtao** [comment]
Also a similar question appeared here: https://github.com/arangodb/arangodb-java-driver/issues/364#issuecomment-706921396

**Comment by DerekHou** [comment]
> Also a similar question appeared here: [#364 (comment)](https://github.com/arangodb/arangodb-java-driver/issues/364#issuecomment-706921396)

@rashtao After upgrading the driver to 6.8.0,  I got the stacktrace occasionally as below:

2020-12-17 09:12:23.473 ERROR 7 --- [pool-1945-thread-1] c.a.i.v.internal.VstConnection           : Got exception while performing keepAlive request:

com.arangodb.ArangoDBException: java.lang.InterruptedException
        at com.arangodb.internal.velocystream.internal.VstConnectionSync.write(VstConnectionSync.java:100)
        at com.arangodb.internal.velocystream.internal.VstConnectionSync.write(VstConnectionSync.java:34)
        at com.arangodb.internal.velocystream.internal.VstConnection.sendKeepAlive(VstConnection.java:129)
        at com.arangodb.internal.velocystream.internal.VstConnectionSync.doKeepAlive(VstConnectionSync.java:106)
        at com.arangodb.internal.velocystream.internal.VstConnection.keepAlive(VstConnection.java:141)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: null
        at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:404)
        at java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.arangodb.internal.velocystream.internal.VstConnectionSync.write(VstConnectionSync.java:98)
        ... 11 common frames omitted

Does it mean ArangoDB server close the connection again?

**Comment by DerekHou** [comment]
I know why the thread which sends keep alive message was interrupted. The connection was closed due to ttl setting.

**Comment by rashtao** [comment]
The error in the client is thrown due to request timeout during the keep-alive probe request, thrown from here: https://github.com/arangodb/arangodb-java-driver/blob/f3429b2902556762ded608f069cc4caf8c603162/src/main/java/com/arangodb/internal/velocystream/internal/VstConnectionSync.java#L98

In case of disconnection due to idle ttl from the db side, you would see in the coordinator logs something like:  
```
{requests} keep alive timeout, closing stream!
```

**Comment by rashtao** [comment]
Closing due to inactivity, feel free to reopen if the problem persists.
