### ISSUE TITLE
Graalvm native build error

### ISSUE THREAD

**Issue by sahak1an** [arangodb/arangodb-java-driver#556]
```
Detailed message:
Trace: Object was reached by
  reading static field com.arangodb.http.compression.JdkZlibEncoder.EMPTY_BUF
    at <unknown-location>
  registered as read because: null
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:828)
	... 6 more
```

java version - graalvm-jdk-21.0.2+13.1
maven version - 3.9.6

```
new ArangoDB.Builder()
                .host("localhost", 8529)
                .user("...")
                .password("...")
                .compression(Compression.NONE)
                .maxConnections(8)
                .build();
```

**Comment by rashtao** [comment]
Can you please report the error as well? It should be logged before the lines that you reported.

**Comment by rashtao** [comment]
Closing as resolved, please reopen in case of further questions.
