### ISSUE TITLE
Driver V4.1.0 Connection reset issues

### ISSUE THREAD

**Issue by aznwarmonkey** [arangodb/arangodb-java-driver#68]
I am trying to use the ArangoDB driver version 4.1.0 without any success.  Here's a snippet of code i am using to connect to my ArangoDB cluster: 
`final ArangoDB arangoDB = new ArangoDB.Builder().host(arangoDBHost).port(dbPort).useSsl(false).build();`

This is the stack trace i am getting:

`Exception in thread "main" com.arangodb.ArangoDBException: java.net.SocketException: Connection reset
	at com.arangodb.internal.velocystream.ConnectionSync.write(ConnectionSync.java:111)
	at com.arangodb.internal.velocystream.CommunicationSync.send(CommunicationSync.java:137)
	at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:119)
	at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:42)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:58)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:47)
	at com.arangodb.ArangoDB.getVersion(ArangoDB.java:297)
	at main.InsertGraph2.main(InsertGraph2.java:22)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.arangodb.internal.velocystream.Connection.readBytesIntoBuffer(Connection.java:210)
	at com.arangodb.internal.velocystream.ConnectionSync.write(ConnectionSync.java:107)
	... 7 more`

I have tried the coordinator port which is configured to 8530 AND the DB port which is configured to 8529 without success.  On the other hand when I use the driver version 3.1.x it works fine.  Is there other configurations i am missing?

Thanks

**Comment by Freak5M** [comment]
Hello,

I got the same error yesterday, my mistake was due to the version of my database.
I had a version 3.0 while the 4.1 driver requires 3.1

Hope it helps ;)

**Comment by aznwarmonkey** [comment]
Thank you, I have verified that i am using 3.0.10.  Will revisit this once I can upgrade to 3.1.
