### ISSUE TITLE
Calls to ArangoDataBase (3.0.12) using ArangoDB instance using (4.1.3) arango-java driver is failing due to reached end of stream exception

### ISSUE THREAD

**Issue by ArangoRaghav** [arangodb/arangodb-java-driver#85]
Hi All,

Below is the stack captured related to this issue:
com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
at com.arangodb.internal.velocystream.ConnectionSync.write(ConnectionSync.java:111)
at com.arangodb.internal.velocystream.CommunicationSync.send(CommunicationSync.java:137)
at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:119)
at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:42)
at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:58)
at com.arangodb.ArangoDB.createDatabase(ArangoDB.java:273)
...
...
...
Caused by: java.io.IOException: Reached the end of the stream.
at com.arangodb.internal.velocystream.Connection.readBytesIntoBuffer(Connection.java:212)
at com.arangodb.internal.velocystream.ConnectionSync.write(ConnectionSync.java:107)

### com.arangodb.internal.velocystream.Connection.java:
protected void readBytesIntoBuffer(final byte[] buf, final int off, final int len) throws IOException {
		for (int readed = 0; readed < len;) {
			final int read = inputStream.read(buf, off + readed, len - readed);
			if (read == -1) {
				throw new IOException("Reached the end of the stream.");
			} else {
				readed += read;
			}
		}
	}

## Arangodb version is:
[@@@ sbin]# ./arangod --version
3.0.12
architecture: 64bit
asan: false
asm-crc32: true
boost-version: 1.61.0b1
build-date: YYYY-MM-DD HH:MM:SS
compiler: gcc
cplusplus: 201103
endianness: little
fd-client-event-handler: poll
fd-setsize: 1024
icu-version: 54.1
jemalloc: true
libev-version: 4.22
maintainer-mode: false
openssl-version: OpenSSL 1.0.1e-fips 11 Feb 2013
rocksdb-version: 4.8.0
server-version: 3.0.12
sizeof int: 4
sizeof void*: 8
sse42: false
tcmalloc: false
v8-version: 5.0.71.39
vpack-version: 0.1.30
zlib-version: 1.2.8

## Arango java driver used is:
com.arangodb
arangodb-java-driver
4.1.3

## VelocyStream protocol support:
When I tried to specify the vpp (velocystream protocol related) command line input to start the arangodb server to solve this issue its not starting (FATAL invalid endpoint issue as shown below).It is starting with tcp endpoint option as expected.

Let me know whether 3.0.12 arango db version has issues related to this vpp/vst acceptance as tried below.

[@@@ sbin]# ./arangod --server.endpoint tcp://xxx:8529
2016-12-27T09:19:48Z [27191] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
2016-12-27T09:19:48Z [27191] INFO file-descriptors (nofiles) hard limit is 4096, soft limit is 1024
2016-12-27T09:19:48Z [27191] INFO ArangoDB 3.0.12 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.1e-fips 11 Feb 2013
2016-12-27T09:19:48Z [27191] INFO loaded database '_system' from '/var/lib/arangodb3/databases/database-1'
2016-12-27T09:19:48Z [27191] INFO loaded database 'testDb' from '/var/lib/arangodb3/databases/database-1289'
2016-12-27T09:19:48Z [27191] INFO the server has 4 (hyper) cores, using 1 scheduler thread(s), 4 dispatcher thread(s)
2016-12-27T09:19:48Z [27191] INFO JavaScript using startup '/usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
2016-12-27T09:19:49Z [27191] INFO In database 'testDb': Database is up-to-date (30012/standalone/existing)
2016-12-27T09:19:49Z [27191] INFO In database '_system': Database is up-to-date (30012/standalone/existing)
2016-12-27T09:19:49Z [27191] INFO using endpoint 'http+tcp://xxxx:8529' for non-encrypted requests
2016-12-27T09:19:49Z [27191] INFO Authentication is turned off
2016-12-27T09:19:50Z [27191] INFO ArangoDB (version 3.0.12 [linux]) is ready for business. Have fun!

[@@@ sbin]# ./arangod --server.endpoint vpp://xxxx:8529
2016-12-27T09:20:34Z [27425] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
2016-12-27T09:20:34Z [27425] FATAL invalid endpoint 'vpp://xxxx:8529'

[@@@ sbin]# ./arangod --server.endpoint tcp+vpp://xxxx:8529
2016-12-27T09:21:11Z [27440] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
2016-12-27T09:21:11Z [27440] FATAL invalid endpoint 'tcp+vpp://xxxx:8529'
[@@@/usr/sbin]# ps -ef | grep "arango"
root 27490 21712 0 04:22 pts/4 00:00:00 grep --color=auto arango

[@@@ sbin]# ./arangod --server.endpoint vst+tcp://xxxx:8529
2016-12-27T09:22:39Z [27540] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
2016-12-27T09:22:39Z [27540] FATAL invalid endpoint 'vst+tcp://xxxx:8529'
[@@@ sbin]# ps -ef | grep "arango"
root 27652 21712 0 04:24 pts/4 00:00:00 grep --color=auto arango

**Comment by christian-lechner** [comment]
Your ArangoDB version (3.0.12) and your Java driver version (4.1.3) do not match. You have two possibilities: 
- upgrade ArangoDB to 3.1 or 
- downgrade driver to 3.0

Taken from the [readme](https://github.com/arangodb/arangodb-java-driver/blob/master/README.md#supported-versions):
<table>
<tr><th>arangodb-java-driver</th><th>ArangoDB</th><th>network protocol</th><th>Java version</th></tr>
<tr><td>4.1.x</td><td>3.1.x</td><td>VelocyStream</td><td>1.6+</td></tr>
<tr><td>3.0.x</td><td>3.0.x</td><td>HTTP</td><td>1.6+</td></tr>
</table>

**Comment by ArangoRaghav** [comment]
Thanks for the info.Will try on this combination.
