### ISSUE TITLE
Error getting Document by key with punctuation characters

### ISSUE THREAD

**Issue by amtemkin** [arangodb/arangodb-java-driver#97]
Hi.

When getting Document with the value contains punctuation characters is thrown ArangoDBException.

For example
ArangoDatabase db...
db.getDocument("MyCollection/myKey+", MyClass.class);

Result
com.arangodb.ArangoDBException: Response: 404, Error: 1202 - document not found
	at com.arangodb.internal.velocystream.Communication.checkError(Communication.java:104)
	at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:120)
	at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:40)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:58)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:47)
	at com.arangodb.ArangoCollection.getDocument(ArangoCollection.java:210)
	at com.arangodb.ArangoDatabase.getDocument(ArangoDatabase.java:598)
....

Some logs
17:46:27.377 [main] DEBUG com.arangodb.internal.velocystream.CommunicationSync - Send Message (id=5, head=[1,1,"xxx",1,"\/_api\/document\/MyCollection\/myKey+",{},{}], body={})
17:46:27.377 [main] DEBUG com.arangodb.internal.velocystream.Connection - Send chunk 1:1 from message 5
17:46:27.378 [main] DEBUG com.arangodb.internal.velocystream.Connection - Received chunk 1:1 from message 5
17:46:27.379 [main] DEBUG com.arangodb.internal.velocystream.ConnectionSync - Received Message (id=5, head=[1,2,404], body={"error":true,"errorMessage":"document not found","code":404,"errorNum":1202})
17:46:27.386 [main] DEBUG com.arangodb.ArangoCollection - Response: 404, Error: 1202 - document not found

I am using the java driver v4.1.7, and ArangoDB v.3.1.4

Best
Aleksander

**Comment by mpv1989** [comment]
Hi Aleksander,
thanks for reporting this bug. I fixed it. You can test it with current snapshot version `4.1.8-SNAPSHOT`. I will release a new version (`4.1.8`) within this week.

Thanks & Best
Mark

**Comment by amtemkin** [comment]
Hi,
Thank you so much.

Best
Aleksander

**Comment by mpv1989** [comment]
fixed in version 4.1.8
